---
layout:   post
title:    "新三板培训手册"
category: share 
tags:     
    -  
    -   
description: 
published: false
status:    process
---

> 我目前在一家私募机构工作，主要负责中小企业挂牌新三板。由此，我会在网站上放一些新三板培训的内容分享。


# 《公司治理与信息披露指南》

> 公司在成长过程中，特别是从非公众公司走向公众公司，需要经历一系列的“基因改造”流程，公司规范治理是其中最重要的环节之一。从公司内部生长角度来看，公司摆脱“人合”的组织架构，逐渐走向“资合”，开始建立现代企业法人治理结构，成为公司走向成熟、稳健发展的起点。企业为了获得发展也需要突破内源融资的依赖，转向外源融资。引入外部资金和职业经理人的过程不可避免地会产生委托代理等问题，从而对公司治理和信息对称等提出要求。规范的公司治理结构有助于公司提升经营决策的有效性、科学性以及风险防控能力。例如，有效的公司治理结构可以避免家族型企业因“一言堂”带来的经营风险。从公司外部投资者角度来看，公司的规范治理，能有效保证投资者的资金安全和运用到位，达到投资安全和增值的目的。作为公众公司治理的一个重要方面，挂牌公司需要进行持续信息披露，以便及时准确全面地向市场展示自身治理结构的规范性，以及经营优势、风险等信息，从而确保市场参与各方能对挂牌公司运营情况及时了解，增强挂牌公司对外部投资者的吸引力。为此，挂牌公司需要依法制定公司章程，建立高效运转的、兼顾公司特点的股东大会、董事会、监事会和管理层（即三会一层）的架构体系，激励相容的内部管理和控制制度，权责明晰、有效制衡的管理机制，注重信息披露和投资者关系管理，切实提升公司治理水平和透明度。
>
> 与此同时，全国股份转让系统作为全国性公开证券交易场所，其挂牌交易的各类证券同上市公司发行的证券一样，对发行主体不确定性和运营风险非常敏感，挂牌公司相关信息的披露，将对挂牌公司发行的各类证券交易定价产生直接甚至决定性的影响，并据此引导社会资源的配置。因此，为确保市场具有高效的价格发现功能，推动社会资源的有效配置，提升挂牌公司对外部资源的吸引力，全国股份转让系统特别强调挂牌公司的持续信息披露职责，要求挂牌公司在主办券商的持续督导下，及时、准确、完整地披露半年报和年报，以及其他重大事项。
>
> 为提高挂牌公司治理水平，提升信息披露质量，打造公开透明的市场运行机制，增强挂牌公司持续规范运作水平，本手册尝试回答了挂牌公司、主办券商等较为关注的一些公司治理和信息披露问题，供参考。

## 一、公司治理

### （一）作为公众公司，全国股份转让系统挂牌公司在公司治理机制方面有无特殊规定？

挂牌公司应当有健全的公司治理机制。公司应按规定建立股东大会、董事会、监事会和高级管理层组成的公司治理架构，并按照《公司法》、《非上市公众公司监督管理办法》（以下简称《非公办法》）及《非上市公众公司监管指引第3号章程必备条款》（详见：全国股份转让系统官方网站www.neeq.com.cn或www.neeq.cc“法律规则”一栏）等规定建立相应的公司治理制度，并能规范有效运行，保证股东权益。

### （二）全国股份转让系统对挂牌公司章程的制定有无特殊规定？

全国股份转让系统对挂牌公司章程的制定有具体的规定。挂牌公司除应依照《公司法》等相关规定制定公司章程外，还应遵照《非上市公众公司监管指引第3号-章程必备条款》的要求。

如章程应当载明保障股东享有知情权、参与权、质询权和表决权的具体安排；公司为防止股东及其关联方占用或者转移公司资金、资产及其他资源的具体安排；公司控股股东和实际控制人的诚信义务；明确须提交股东大会审议的重大事项的范围；载明公司的利润分配制度（详见：全国股份转让系统官方网站www.neeq.com.cn或www.neeq.cc“法律规则”一栏）。

### （三）全国股份转让系统对挂牌公司董、监、高人员任职资格方面有无特殊要求？

全国股份转让系统对挂牌公司董、监、高人员任职资格方面无特殊要求，董、监、高人员应当遵守法律、行政法规和公司章程的相关规定，对公司负有忠实义务和勤勉义务。挂牌公司应当在挂牌时向全国股份转让系统报备董事、监事及高级管理人员的任职、职业经历及持有挂牌公司股票情况。依照《公司法》第一百四十六条的有关规定，有下列情形之一的，不得担任公司的董事、监事、高级管理人员：

- （1）无民事行为能力或者限制民事行为能力。

- （2）因贪污、贿赂、侵占财产、挪用财产或者破坏社会主义市场经济秩序，被判处刑罚，执行期满未逾五年，或者因犯罪被剥夺政治权利，执行期满未逾五年。

- （3）担任破产清算的公司、企业的董事或者厂长、经理，对该公司、企业的破产负有个人责任的，自该公司、企业破产清算完结之日起未逾三年。

- （4）担任因违法被吊销营业执照、责令关闭的公司、企业的法定代表人，并负有个人责任的，自该公司、企业被吊销营业执照之日起未逾三年。

- （5）个人所负数额较大的债务到期未清偿。

## 二、持续信息披露概述

### （一）持续信息披露义务有哪些？

根据《全国中小企业股份转让系统挂牌公司信息披露细则（试行）》（以下简称《信息披露细则》）相关规定，挂牌公司信息披露包括挂牌前的信息披露及挂牌后持续信息披露，其中挂牌后持续信息披露包括定期报告和临时报告。

挂牌公司应当披露的定期报告包括年度报告、半年度报告，鼓励但不强制披露季度报告；临时报告是指除定期报告以外的公告，例如股东大会决议公告、董事会决议公告、监事会决议公告以及对外投资公告等。

### （二）信息披露义务人包括哪些主体？

信息披露义务人包括申请挂牌公司、挂牌公司及其董事（会）、监事（会）、高级管理人员、股东、实际控制人、收购人及其他相关信息披露义务人。

挂牌公司及相关信息披露义务人应当及时、公平地披露所有对公司股票及其他证券品种转让价格可能产生较大影响的信息，并保证信息披露内容的真实、准确、完整，不存在虚假记载、误导性陈述或重大遗漏。

### （三）企业、大股东与董、监、高的职责分别有哪些？

根据《公司法》、《证券法》、《非公办法》、《全国中小企业股份转让系统业务规则（试行）》（以下简称《业务规则》）、《信息披露细则》等相关规定：挂牌公司应当按照法律、行政法规、部门规章、全国股份转让系统相关业务规定完善公司治理，确保所有股东，特别是中小股东享有平等地位，充分行使合法权利；应当依据《公司法》及有关非上市公众公司章程必备条款的规定制定公司章程并披露，依照公司章程的规定，规范重大事项的内部决策程序。

挂牌公司与控股股东、实际控制人及其控制的其他企业应实行人员、资产、财务分开，各自独立核算、独立承担责任和风险。

控股股东、实际控制人及其控制的其他企业应切实保证挂牌公司的独立性，不得利用其股东权利或者实际控制能力，通过关联交易、垫付费用、提供担保及其他方式直接或者间接侵占挂牌公司资金、资产，损害挂牌公司及其他股东的利益。

公司的董事、监事、高级管理人员应当忠实、勤勉地履行职责，保证公司披露信息的真实、准确、完整、及时。董事、监事、高级管理人员不得利用职权收受贿赂或者其他非法收入，不得侵占公司财产。

挂牌公司、控股股东及董事、监事和高级管理人员作为信息披露义务人，应当按照法律、行政法规和中国证监会的规定，真实、准确、完整、及时地披露信息，并应向所有投资者同时公开披露信息，不得有虚假记载、误导性陈述或者重大遗漏。

### （四）信息披露负责人的主要职责有哪些？

根据全国股份转让系统《信息披露细则》、《业务规则》等相关规定，挂牌公司设有董事会秘书的，由董事会秘书负责信息披露管理事务；未设董事会秘书的，挂牌公司应指定一名具有相关专业知识的人员负责信息披露管理事务，并向全国股份转让系统报备。上述人员离职无人接替或因故不能履行职责时，公司董事会应当及时指定一名高级管理人员负责信息披露事务并披露。
挂牌公司董事会秘书或信息披露事务负责人应按照全国股份转让系统相关规定编写公告文稿，并准备备查文件。负责信息披露管理事务的人员应列席公司的董事会和股东大会。

### （五）主办券商等中介机构的职责有哪些?

根据《非公办法》、《业务规则》的相关规定，主办券商、律师事务所、会计师事务所及其他证券服务机构，应当勤勉尽责、诚实守信，认真履行审慎核查义务，按照依法制定的业务规则、行业执业规范和职业道德准则发表专业意见，保证所出具文件的真实性、准确性和完整性，并接受中国证监会的监管。

主办券商应对挂牌公司拟披露的信息披露文件进行审查，履行持续督导职责。

### （六）信息披露的操作流程？

根据2014年12月31日发布的《全国中小企业股份转让系统挂牌公司持续信息披露业务指南（试行）》相关规定，挂牌公司董事会秘书或者信息披露事务负责人应当通过编制端编制披露文件，编制工具里没有明确给出模板的临时公告，由挂牌公司根据有关规定自行编制。挂牌公司准备好披露文件后, 应将包括加盖董事会章的公告纸质文件及相应电子文档，其中电子文档包括定期报告或临时公告正文及相应XBRL文件（自行编制的除外）送达主办券商。主办券商对拟披露文件进行事前审查，使用“全国中小企业股份转让系统数字证书”通过报送端报送披露文件，披露文件包括文件正文（PDF格式）及XBRL文件（自行编制的除外）；信息披露系统在规定的时间段中将披露文件的正文自动发送至全国股份转让系统指定信息披露平台。具体操作流程示意图如下：

### （七）全国股份转让系统如何对信息披露进行监管？

全国股份转让系统对挂牌公司的日常监管主要是以信息披露为核心、依托主办券商持续督导的自律监管。具体方式为：主办券商对挂牌公司的信息披露和业务办理进行事先审查和把关，全国股份转让系统进行事后审查和监管。在监管实践中，全国股份转让系统探索出了由监管员对挂牌公司进行日常监管的方法。

日常监管主要包括四个方面：

- 一是以主办券商来划分监管员对挂牌公司的监管分工。每个监管员负责几家主办券商推荐并持续督导的挂牌公司日常监管工作，以利于保持监管的连续性和稳定性，提高监管和沟通的效率。

- 二是通过监管员对挂牌公司信息披露文件事后审查的方式，对信息披露文件中涉及重大事项以及风险外溢程度高的挂牌公司进行监管。

- 三是主要通过引导、培训、督促的方式，对挂牌公司进行规范和监管。

- 四是通过内部晨会及日志的形式及时将监管情况进行汇总，并传递到每个监管员；在对重点监管事项及重点公司处理后，及时形成监管案例，并建立标准化的处理程序。

## 三、定期报告披露实务

### （一）需要披露的定期报告种类有哪些？

挂牌公司应当披露的定期报告包括年度报告、半年度报告。全国股份转让系统鼓励但不强制要求挂牌公司披露季度报告。

### （二）定期报告的披露时限要求是什么？

挂牌公司应当在每个会计年度结束之日起四个月内编制并披露年度报告，在每个会计年度的上半年结束之日起两个月内披露半年度报告；披露季度报告的，公司应当在每个会计年度前三个月、九个月结束后的一个月内披露，且第一季度报告的披露时间不得早于上一年的年度报告。

### （三）年度报告的主要内容及审计要求有哪些？

挂牌公司的年度报告须参照全国股份转让系统发布的《全国中小企业股份转让系统挂牌公司年度报告内容与格式指引（试行）》（以下简称《年报内容与格式指引》）的要求进行披露，主要内容包括重要提示、目录和释义，公司简介，会计数据和财务指标摘要，管理层讨论与分析，重要事项，股本变动及股东情况，董事、监事、高级管理人员及核心员工情况，公司治理及内部控制，财务报告，备查文件目录等十个章节。

挂牌公司年度报告中的财务报告必须经具有证券期货相关业务资格的会计师事务所审计。

### （四）半年度报告的主要内容及审计要求有哪些？

挂牌公司的半年度报告须参照全国股份转让系统发布的《全国中小企业股份转让系统挂牌公司半年度报告内容与格式指引（试行）》（以下简称《半年报内容与格式指引》）要求进行披露，主要内容包括公司半年大事记，声明与提示，目录，正文及备查文件目录等。正文包括基本信息，财务信息和非财务信息。

挂牌公司半年度报告中的财务报告无须经审计，若挂牌公司自愿进行审计，需聘请具有证券期货相关业务资格的会计师事务所审计。

### （五）全国股份转让系统对定期报告的审查标准和流程是什么？

全国股份转让系统对定期报告的审查标准是按照《信息披露细则》、《年报内容与格式指引以及《半年报内容与格式指引》等规则中对定期报告的要求制定。

全国股份转让系统对定期报告进行事后审查，对在信息披露平台已经披露的定期报告进行审查。挂牌公司及相关信息披露义务人应该确保定期报告中所包含内容真实、准确、完整，不存在虚假记载、误导性陈述或重大遗漏。具体流程如下：

- （1）监管员按照全国股份转让系统对年报及半年报的相关要求对已披露的年报及半年报进行内容与格式审查；

- （2）对需要调查、了解情况或问题的公司，通过指定邮箱发给主办券商，请主办券商和挂牌公司进行说明；

- （3）对主办券商和挂牌公司关于反馈意见的回复进行核查及讨论，必要情况下，可要求主办券商和挂牌公司进行进一步说明；

- （4）得出关于年报审查的结论性意见，需要更正的，提请主办券商督导挂牌公司及时更正年报。


### （六）全国股份转让系统对定期报告不规范行为如何处理？

全国股份转让系统对定期报告进行事后审查，确保定期报告的真实、准确、完整。对于审查中发现的定期报告披露不规范行为，情节较轻者，我们将会与主办券商和挂牌公司进行沟通，要求其对定期报告进行更正，并更新相应的定期报告；情节较为严重者，除要求其对定期报告进行更正外，我们还将会针对挂牌公司及相关主体在信息披露过程中和券商持续督导过程中的违规行为，根据《业务规则》中的相关规定，对相应的责任人采取自律监管措施或纪律处分措施，违规行为达到中国证监会稽查标准的，将及时移交中国证监会处理。

### （七）如何对定期报告进行修改和补充？

定期报告在全国股份转让系统网站披露后，挂牌公司或主办券商如发现有重大错误或遗漏需要更正或补充的，挂牌公司应依照《全国中小企业股份转让系统挂牌公司持续信息披露业务指南（试行）》的规定发布更正或补充公告，并重新披露相关公告。原已披露的公告不做撤销。

## 四、临时报告披露实务

### （一）哪些属于应当披露的重大信息？

应当披露的重大信息是指对挂牌公司股票及相关产品转让价格可能产生较大影响的事项。董事会认为对股票及相关产品价格可能产生较大影响的信息，公司也应作为重大信息进行披露。挂牌公司控股子公司发生的对挂牌公司股票及相关产品转让价格可能产生较大影响的信息，视同挂牌公司的重大信息。

### （二）需要披露临时报告的情形有哪些？

- （1）挂牌公司召开董事会会议，会议内容涉及应当披露的重大信息，公司应当以临时公告的形式及时披露；决议涉及根据公司章程规定应当提交经股东大会审议的收购与出售资产、对外投资（含委托理财、委托贷款、对子公司投资等）等事项，公司应当在决议后及时以临时公告的形式披露。

- （2）挂牌公司召开监事会会议，涉及应当披露的重大信息，公司应当以临时公告的形式披露。

- （3）挂牌公司召开股东大会，应当在会议结束后两个转让日内将相关决议以临时公告的形式披露。

- （4）除日常关联交易之外的其他关联交易，挂牌公司应当经过股东大会审议并以临时公告的形式披露。

- （5）挂牌公司对涉案金额占公司最近一期经审计净资产绝对值10%以上的重大诉讼、仲裁事项以临时公告的形式披露。

- （6）挂牌公司应当在董事会审议通过利润分配或资本公积转增股本方案后，以临时公告的形式披露方案具体内容，并于实施方案的股权登记日前披露方案实施公告。

- （7）股票转让被全国股份转让系统认定为异常波动的，挂牌公司应当于次一股份转让日披露异常波动公告。

- （8）公共媒体传播的消息可能或者已经对公司股票转让价格产生较大影响的，挂牌公司应当及时向主办券商提供有助于甄别传闻的相关资料，并决定是否发布澄清公告。

- （9）实行股权激励计划的挂牌公司，应当严格遵守全国股份转让系统有关规定，并履行披露义务。

- （10）限售股份在解除转让限制前，挂牌公司应披露相关公告。

- （11）在挂牌公司中拥有的权益份额达到该公司总股本5%及以上的股东，其拥有权益份额变动达到全国股份转让系统规定标准的，该股东应当按照要求及时通知挂牌公司并披露权益变动公告。

- （12）挂牌公司和相关信息披露义务人披露承诺事项的，应当严格披露承诺事项。

- （13）全国股份转让系统对挂牌公司实行风险警示或作出股票终止挂牌决定后，公司应当及时披露。

- （14）挂牌公司出现以下情形之一的，应当自事实发生之日起两个转让日内以临时公告的形式披露：

   - ①控股股东或实际控制人发生变更；

   - ②控股股东、实际控制人或者其关联方占用资金；

   - ③法院裁定禁止有控制权的大股东转让其所持公司股份；

   - ④任一股东所持公司5%以上股份被质押、冻结、司法拍卖、托管、设定信托或者被依法限制表决权；

   - ⑤公司董事、监事、高级管理人员发生变动，董事长或者总经理无法履行职责；

   - ⑥公司减资、合并、分立、解散及申请破产的决定，或者依法进入破产程序、被责令关闭；

   - ⑦董事会就并购重组、股利分派、回购股份、定向发行股票或者其他证券融资方案、股权激励方案形成决议；

   - ⑧变更会计师事务所、会计政策、会计估计；

   - ⑨对外提供担保（挂牌公司对控股子公司担保除外）；

   - ⑩公司及其董事、监事、高级管理人员、公司控股股东、实际控制人在报告期内存在受有权机关调查、司法纪检部门采取强制措施、被移送司法机关或追究刑事责任、中国证监会稽查、中国证监会行政处罚、证券市场禁入、认定为不适当人选，或收到对公司生产经营有重大影响的其他行政管理部门处罚；

   - 11因前期已披露的信息存在差错、未按规定披露或者虚假记载，被有关机构责令改正或者经董事会决定进行更正；

   - 12主办券商或全国股份转让系统认定的其他情形。

### （三）公司三会决议是否必须披露？

董事会决议涉及应当披露的重大信息的，应当以临时公告形式及时披露；决议涉及根据公司章程应提交股东大会审议的收购与出售资产、对外投资等事项，公司应在决议后及时以临时公告形式披露。

监事会决议涉及应当披露的重大信息的，应当以临时公告形式及时披露。
挂牌公司的股东大会决议应在会议结束后两个转让日内进行披露。

### （四）披露临时报告的时间要求是什么？

挂牌公司应当在临时报告所涉及的重大事件最先触及下列任一时点后及时履行首次披露义务：

- （1）董事会或者监事会作出决议时。

- （2）签署意向书或者协议（无论是否附加条件或者期限）时。

- （3）公司（含任一董事、监事或者高级管理人员）知悉或者理应知悉重大事件发生时。


对挂牌公司股票转让价格可能产生较大影响的重大事件正处于筹划阶段，虽然尚未触及上述时点，但出现下列情形之一的，公司亦应履行首次披露义务：

- （1）该事件难以保密。

- （2）该事件已经泄漏或者市场出现有关该事件的传闻。

- （3）公司股票及其衍生品种交易已发生异常波动。


挂牌公司应该及时履行信息披露义务，所谓“及时”是指自起算日或触及《信息披露细则》规定的披露时点起两个转让日内，另有规定的除外。


### （五）全国股份转让系统对临时报告的审查标准和流程是什么？

目前，临时报告的审查标准是按照《业务规则》及《信息披露细则》等有关规定制定。

全国股份转让系统对挂牌公司及其他信息披露义务人已披露的临时公告信息进行审查，具体流程及审查重点如下：

- （1）信息披露审查人员按照《业务规则》、《信息披露细则》以及临时公告模板的要求审查临时公告的合规性，信息披露的及时性、真实性、准确性及完整性。

- （2）对需要调查、了解情况或问题的公司，要求主办券商和挂牌公司进行说明。

- （3）对确实不符合信息披露相关规定、存在较大错误或遗漏的，通知主办券商督促挂牌公司进行更正或补充处理。对于情节较为严重的，将对挂牌公司及相关责任人采取自律监管措施。

### （六）全国股份转让系统对临时报告不规范行为如何处理？

全国股份转让系统对临时报告进行事后审查，确保临时报告的真实、准确、完整。对于审查中发现的临时报告披露不规范行为，情节较轻者，我们将会与主办券商和挂牌公司进行沟通，要求其对临时报告进行更正，并更新相应的临时报告；情节较为严重者，除要求其对临时报告进行更正外，我们还将会针对挂牌公司及相关主体在信息披露过程中和券商持续督导过程中的违规行为，根据《业务规则》中的相关规定，对相应的责任人采取自律监管措施或纪律处分措施，违规行为达到中国证监会稽查标准的，将及时移交中国证监会处理。

### （七）如何对临时报告进行修改和补充？

目前，临时报告在全国股份转让系统网站披露后，挂牌公司或主办券商如发现有重大错误或遗漏需要更正或补充的，挂牌公司应依照《全国中小企业股份转让系统挂牌公司持续信息披露业务指南（试行）》的规定发布更正或补充公告，并重新披露相关公告。原已披露的公告不做撤销。

### （八）全国股份转让系统发布的临时公告模板是否强制适用？

全国股份转让系统于2014年7月21日公布了经修订的《全国中小企业股份转让系统临时公告格式模板》（详见：全国股份转让系统官方网站[www.neeq.com.cn](www.neeq.com.cn)或[www.neeq.cc](www.neeq.cc) “法律规则”下的“服务指南”一栏），挂牌公司应当按照模板规定的内容及公司具体情况，规范披露临时公告。