---
layout:   post
title:    "讲座课件汇总"
category:  stock
tags:     
    - 国信
    - 股票
description: 
published: false
status:    process
---

我在国信厦门部工作了整一年时间，期间主要任职于金融顾问中心，担任投资顾问助理。在这段时间里，我从一个学究气息浓厚的学生，逐步成长为务实、接地气的行业研究与股票分析员。在此时间段内，我也经历了 A 股从多年的熊市走出，开始这一波贯绝中外的疯牛行情。有过憧憬，也有过迷惘。无论如何，我将结束在这里的工作，开启新的职业生涯。

> 这里我要感谢厦门部的各位领导对我的栽培，特别是感谢金顾中心的张博士，引领我踏进股市的大千世界。

# 港股通业务

沪港通业务于 11 月 17 日正式开通，之前整个资本市场一直都在憧憬外资通过沪股通的渠道投资 A 股市场，这也是此次牛市发韧。厦门营业部很快意识到港股通业务将呈现爆发性的提升，因此，领导希望金顾能够提供相应的服务产品。

当时由博士推荐我来负责本次港股通业务的产品设计。以下是我竞聘时制作的课件。


<iframe src="http://7xkojm.com1.z0.glb.clouddn.com/papers/方莲-港股通.pdf" 
style="width:100%; height:520px;" frameborder="0">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="http://7xkojm.com1.z0.glb.clouddn.com/papers/方莲-港股通.pdf">
  全屏查看
</a>
</p>

# 结构性牛市下的投资策略

2015年1月9日， 大盘经历了宽幅震荡，并形成一个局部的圆弧顶。当时整个市场都在怀疑牛市或许将面临回调。在周五的夕会上，我回顾了一周的行情，并根据本次牛市的逻辑基础，提速本次牛市远未到顶，但基本的行情将面临分化。即，当时由券商、银行、保险共同组成的「金三胖」或将不再延续大涨行情，市场即将转入结构性的行情特征。以下是我在夕会做的课件。


<iframe src="http://7xkojm.com1.z0.glb.clouddn.com/papers/20150109-初生「牛」犊不怕「虎」.pdf" 
style="width:100%; height:520px;" frameborder="0">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="http://7xkojm.com1.z0.glb.clouddn.com/papers/20150109-初生「牛」犊不怕「虎」.pdf">
  全屏查看
</a>
</p>


# A 股市场大势研判

今年春节火了一把「微信·红包」，群里纷纷慷慨解囊。同时，A股也经历了一大波的红包行情。在此背景下，我继续看好A股上涨的基本逻辑不变。


<iframe src="http://7xkojm.com1.z0.glb.clouddn.com/papers/20150213-抢「红包」哪家强.pdf" 
style="width:100%; height:520px;" frameborder="0">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="http://7xkojm.com1.z0.glb.clouddn.com/papers/20150213-抢「红包」哪家强.pdf">
  全屏查看
</a>
</p>


# 三维丝：东山之志始末不渝

三维丝是厦门本地的一家环保上市公司。厦门营业部想针对厦门本地上市公司提供一些特色的服务产品，张博士指派我去研究三维丝。

<iframe src="http://7xkojm.com1.z0.glb.clouddn.com/papers/300056-三维丝.pdf" 
style="width:100%; height:520px;" frameborder="0">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="http://7xkojm.com1.z0.glb.clouddn.com/papers/300056-三维丝.pdf">
  全屏查看
</a>
</p>

# 大象「如何」起舞

这是一次关于如何看待时下行情的讲座。当时正值「两会」召开前夕，我推荐从其中挖掘题材股。

两会期间被轮番爆炒，热词抢占A股前沿

- 环保是一个「大产业」： 支柱产业定位，环保行业政策
- 国资改革：全面推进
- 互联网+：不仅是改造传统产业，而是「重造」整个生态
- 工业4.0：中国制造2025
- 政策为经济兜底：基建、地产、有色、金属


<iframe src="http://7xkpge.com1.z0.glb.clouddn.com/20150313/20150313.html" style="width:100%; height:520px;">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="http://7xkpge.com1.z0.glb.clouddn.com/20150313/20150313.html">
  全屏查看
</a>
</p>

# 孔雀東南飛

沪港通自从正式开通后，由于国内A股市场已经风生水起、红红火火的经历了一大波超级疯牛行情，因此，国内资金较少发生外流。从沪港通双向的资金流向来看，我发现，海外资金通过沪股通渠道大量的流入国内，而资金走港股通外流的体量则非常少。可以说，整个港股通似乎被市场遗忘了。

然而，这种情况却随着证监会宣布险资可以购买香港市场的创业板股票、公募资金有望南下流向香港市场，以及后续的两地基金互认等，如此多的政策红利集中在今年的4月初爆发。在短短的几个交易日里，香港市场走出了多连阳，许多股票甚至都翻番，乃至多倍。

在这个时间点，我与厦门营业部的同事交流了香港市场的投资机会，并在夕会上做了分享。

** 投资逻辑 **
- 直接受益于资本市场制度红利的券商行业
- AH 股折价率:两地估值溢价。主要是 TMT 类小市值个股
- 稀缺性:市值结构。对于港股来说，优质的 TMT 类公司具备一定的稀缺性
- 股息分红:两地风格偏好。外部投资者偏好于高分红低估值且业绩相对稳定的资产
- 产业竞争力:全球视角
- 一言以蔽之：真正的价值投资！！！


<iframe src="http://7xkpge.com1.z0.glb.clouddn.com/20150403/20150403.html" style="width:100%; height:520px;">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="http://7xkpge.com1.z0.glb.clouddn.com/20150403/20150403.html">
  全屏查看
</a>
</p>











