---
layout:   post
title:    "新三板的“奇葩”名字"
category: stock 
tags:     
    -  
    -   
description: 
published: false
status:    process
---

> 本文根据「新三板在线」报导：[那些新三板的“奇葩”名字：去吧看看](http://www.sanban18.com/Industry/4637.html)

A股主板的匹凸匹、二三四五、天神娱乐、跨境通宝等奇葩名字，已经为众多投资者博得一乐。新三板也有一些很有意思的名字。

比如“去吧看看”，比如“朱老六”、“小白龙”、“阿波罗”、“竹林松大”……

光看名字，你会认为“去吧看看”应该是一家做旅游的公司，或者也会联想到朋友圈“世界很大，我们都去吧看看”这样的流行语。但实际的情况让你大跌眼镜，它是一家做粮油批发零售的公司，业务非常传统。

资料显示，去吧看看成立于2011年5月13日,注册资本668万元，公司2013年和2014年的营业收入分别为173.8万元和1003万元。而且90%以上的业务集中在郑州市区。

公司自己也称资产规模较小，经营稳定性较弱，抵抗市场风险和行业风险的能力仍有待加强。不过在7月27日挂牌新三板后，去吧看看迎来了通过资本市场做大业务的机会。7月31日公司公告称，因重大资产重组停止股票转让。

如果说去吧看看让你摸不着头脑。看到“朱老六”这个名字，估计你就会会心一笑，“老板是不是排行老六呀”。

按照公开转让说明书，公司是由朱家6兄妹组建而成，大股东朱先明排行最小。

朱老六的业务也很传统，其主营业务为腐乳、料酒的生产和销售，其中的腐乳业务超过公司整体业务的96%。在长春当地，朱老六是颇有知名度的公司，公司商标“朱老六”也属于驰名商标。

新三板在线统计，A股的雷人名字，大都是更名取得的，一些公司往往为了迎合时下的热点炒作，取了个奇葩名字。不管是多伦股份更名为匹凸匹，还是科冕木业取名为天神娱乐都属于此类。

而新三板的“奇趣”名字大都和公司成立时取名有关。有些是为了好记；有些是嫁接个国外名人，以加深市场认知度；有些是出于文化内涵考虑。凡此种种，不一而足。

如“小白龙”，尽管和西游记中的白龙马没有半点关系，但也是一家动漫文化公司，旗下的玩具产品主要销往海外。

“阿波罗”、“海明威”、“哥伦布”是典型的傍老外大款的案例。

“阿波罗”是上海一家致力于开拓高端泵产品的高新技术企业，和太阳神牵扯不上关系。

“海明威”的主营业务是线轮和钓竿的研发、生产与销售。当年大文豪海明威写作名著《老人与海》时，不曾想过，半个世纪后会有一家中国的渔具企业，会借助他的名字来提升公司和产品的知名度。

“哥伦布”是商业地产行业的第三方服务提供商。其为商业地产项目提供策划、招商、设计、运营等商业管理服务，这和当年哥伦布发现新大陆不可同日而语。

比较有文化内涵的是“山屿海”，公司全称是安吉山屿海旅游发展股份有限公司，主要业务是向中老年人提供候鸟式旅居度假服务。

同样有些文化内涵的“竹林松大”，公司名字和业务八竿子打不着。其全称是郑州竹林松大科技股份有限公司，所属行业为软件和信息技术服务业,应用领域为城市交通智能化、视频监控。

“天香苑”看似一家房地产公司，实际是一家酵母及酵母衍生物供应商，专业从事酵母抽提物、酵母β-葡聚糖、甘露寡糖等产品的研发、生产及销售。

“回头客”的名字倒是和公司业务有些贴切，其业务主要是饼干、膨化食品、糕点的生产销售。对公司来说，销售中的回头客自然是越多越好。

纵观新三板挂牌的企业，离奇的公司名字仅是少数，或许对于它们来说，在3000多家挂牌海洋中，取个会让你一笑的名字，也是抓住投资者的一种传播捷径。
