---
layout:   post
title:    "私募大佬展望A股2016年"
category:  share
tags:     
    -  
    -   
description: 
published: false
status:    process
---

<p>挥别惊心动魄的2015年，A股2016年又会演绎怎样的行情呢？在新的一年里，投资机会的方向在哪里，我们又该如何布局？对此，券商总体表达了乐观的态度，接下来，看看私募高手们如何看待2016年？</p>

<p><strong>重阳投资总裁王庆：2016年结构化明显</strong></p><p>整个的市场风险已经得到相当的释放，从机会上来讲，支持市场的一些重要基本面的因素本质上没有发生变化。前瞻性的看，2016年可能这个市场将会表现出愈益明显的结构性特征，因为系统性的机会，短期内不大可能再发生，市场将更多的表现出这种慢牛行情的可能性更大。</p>

<p><strong>尚雅投资董事长石波：资产荒的时代还会延续</strong></p><p>资产荒的时代还会延续，因为利率在降低，对收益率优良的资产越来越稀缺，2016年股市仍然是一个平衡，区间在3000点到4000点。从布局来看，2016年要关注新股热和并购热，行业方面，新兴产业的市值我们认为2020年会超越传统产业，其中看好教育、科技、文化、卫生、医疗、体育、美丽产业。</p>

<p><strong>星石投资副总经理王玲：迎来更可靠的5000点</strong></p><p>我们对2016年股市充满了信心，牛市将再现。不仅如此，曾经给人们带来伤痛的5000点，或许会再次被突破，只是这次，我们迎来的可能是更加牢靠的5000点，而不是危机四伏的5000点。</p><p>首先，2016年经济不会出现硬着陆，整体来说经济会有一个企稳复苏的迹象；其次，资金面和政策面。目前政府还是把股市像10年前的房市一样提到非常高的地位。政府的工作重点就是供给侧改革，需要资本市场强有力支持，种种中央的信号表明对资本市场的支持力度2016年还是非常大的。</p><p>我们建议围绕供给侧改革或者十三五掘金，其中梳理三条主线，就是智能制造、节能环保、消费。</p>

<p><strong>菁英时代副总裁罗志鹏：2016年市场更为理性</strong></p><p>未来三到五年，我们看的是比较中性乐观的局面，还是三个层面的问题，可能从改革从转型从创新方面找投资机会。前两项是中国独有的，制度上的转型和行业转型是中国独有的特色。第三个创新就是全球一体，国外在某些领域，特别是硅谷在创新方面还是占据领先地位。</p>

<p><strong>新价值投资投委会主席罗伟广：个股会产生很大泡沫</strong></p><p>我是从草根博弈出来的，去年上半年我们这帮人都很怕，觉得外面人太猛了，加了几百倍杠杆，赚了几百万几千万，散户都来和我讲股票怎么样，所以去年上半年我们很害怕，有些人可能一季度崩，有些人二季度崩，最后崩成这样我们没想到。所有人以为自己是安全的，但是所有人都不懂，没试过，这么一个牛市又有杠杆。2015年试过一次以后不会再发生了，所有人都记住了，所有人都学会了，这是牛市最大的风险，这个风险消失了我们做投资就好做了，因为大家有经验了。但未来我觉得只有个股的行情，因为那么多行情你也支撑不了。所以我觉得指数不会有很大机会，但是个股会产生很大的泡沫。</p>

<p>从布局来看，第一，蓝筹已经两三年没有行情了，2016年很可能发生一次，看好券商、银行、保险；第二，小市值，因为注册制实施之前，会有最后的疯狂，买卖双方的成本降下来了，未来肯定会有很多行情机会。</p>

<p><strong>从容投资董事长吕俊：除了股票外机会很少</strong></p>

<p>2016年最确定的可能是人民币会贬值。然后商品和债券不太好做，因为已经跌了那么多了，剩下的钱不太好挖掘，万一经济一反复，好起来了可能就比较难做。其他地方没什么机会了，只有股票还能提供一些机会，经过这个推导，你会发现还是看好股票。</p><p>其中，股票里面的并购是有机会的，比如各种央企的并购；再一个就是供给侧的改革，会有什么样的举措，我相信供给侧的改革也是结合国企改革，会出现一些举措；最后，还有一些新兴行业的公司，就老老实实成长，去年还觉得他贵，今年可能就不贵了。</p>

<p><strong>景林资产董事长田峰：精选个股</strong></p><p>我们觉得2016年用一句话讲，目前整体估值合理，部分股票太贵，指数可能还是一个震荡，精选个股。</p><p>回想两千年美国的网络泡沫破灭之后很多公司都是在泡沫破灭之前拿到了钱，包括新浪，还有一些不错的互联网公司，都是在2000年之前拿到了钱，后来慢慢起来，通过三四年的精耕细作变成了好公司。两千年之后美国有一个概念，“漂亮50”，如果从这个角度来说会起来一批很好的公司很伟大的公司；另外一个层面就是去库存、去产能，很多行业现在还是处在艰难的去产能阶段，未来去产能之后，有一些细分行业机会也会慢慢涌现出来，过去一两年已经看到一些新的行业已经有这样一些迹象，也有一些这样的公司，从去产能当中活下来了，最后获得了很好的经济效益和快速增长。</p>

<p><strong>品进资产首席权益投资官张雷：明年不会复制今年走势</strong></p>

<p>假设现在有头牛在我们前面，这头牛的前蹄代表的是流动性，后蹄代表的是上市公司，牛的前蹄撑了起来，所以说牛头到了5718点，后来又断了，跌到了两千多点。2016年不会出现这种情况，高的时候五千点，低的时候两千点。</p><p>如果未来还希望出现大的牛市不现实，从降息的幅度来讲空间也好，没有这么大，我们买股票股票涨跌主要看变化，而丰岭资本董事长金斌：出现大牛市不现实不是看现在的流动性强还是弱。我们认为更多的情况下是相对比较平衡的市场。</p><p>如果说风险，A股大部分股票估值偏贵，这是最大的风险。</p>

<p><strong>丰岭资本董事长金斌：出现大牛市不现实</strong></p><p>如果未来还希望出现大的牛市不现实，从降息的幅度来讲空间也好，没有这么大，我们买股票股票涨跌主要看变化，而不是看现在的流动性强还是弱。我们认为明年市场更多的情况下是相对比较平衡的市场。</p><p>如果说风险，A股大部分股票估值偏贵，这是最大的风险。</p><p>第二条，我觉得人民币汇率现在有一点贬值压力，幅度怎么控制，大家可以看到，中国的十年期国债的收益率已经破三了，美国十年期国债收益率大概是2.2到2.3之间，这意味着如果要保持人民币汇率相对比较稳定，明年降息的风险比较小，明年降息的风险没有今年大，而且人民币汇率有很大压力，这个市场有风险。</p><p>另外，A股如果推注册制的话，会造成很大的冲击，如果A股推了注册制，对于基本面比较好的公司是比较大的利好。过去A股涨的最好的股票是壳，过去七八年A股的资源配置是错配的，这很没有效率，二级市场的投资者都希望赚钱，把二级市场的投资资金吸引到经营很差的公司，反而吸引到很多的钱，这是很不正常的市场。</p>

<p><strong>望正资产基金经理韦明亮：传统行业有逆袭可能</strong></p>

<p>判断市场走向，一方面就是看钱，钱多还是钱少。钱多钱少就看利率走向。第二个方面就是股票市场有没有吸引率，就看上市公司有没有增长，如果没有增长的话，预期好不好，虽然现在不好，但是有没有改革的原因使得预期很好。在当下，我们还是认为利率还是会往下走，我们倾向认为216年市场还是会有机会的。如果某个时间段，经济有企稳的可能性。银行股、周期股、地产股可能有很大机会。</p>

<p><strong>弘哲集团创始人董事长郝丹：千股涨停不会出现</strong></p><p>首先，要保持谨慎，同时要有乐观的心态，但是尽量获取一些交易性机会，不要再考虑千股涨停，所有的股票都有一个很好的涨幅，这种现象我估计在未来基本上很小的概率会出现。</p>

<p><strong>华融证券总经理马兹晖：明年是慢牛</strong></p><p>我们认为2016年是慢牛，波动区间在于3400点到3500点。从基本面来看，第一，宏观经济不是太好，但是没有硬着陆的风险，没有系统性风险；第二，从分母端来看，资金成本下降，所以分母应该是很小的。但是分子端复杂一些，因为今年经济不好，分子端会出现结构性改善，现在确实已经取得了一些进展，一些低效企业开始退出市场，高效企业市场份额收入利润可能会出现改善。但是新兴产业总体来说是供不应求的，形势就会更好一些，收入利润也会明显增长，所以分子我认为是结构性改善。总体来看没有系统性风险，分母见效，分子结构性改善是结构性牛市。</p>

