---
layout:   post
title:    "i财富金牌分析师"
category:  strategy
tags:     
    -  
    -   
description: 
published: true
status: publish
output:
  html_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true
    toc: yes
    css: style.css
---


```{r echo=FALSE, warning=FALSE, message=FALSE}
rm(list = ls())
library(rvest)
library(beepr)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
url <- "http://www.icaifu.com/report/sub_list/5/89283.shtml"           ## i财富首页 » 研报频道 » 赵晓光(安信)

link <- url %>% 
  read_html() %>% 
  html_nodes(".fund  td  a") %>% 
  html_attr("href") %>% 
  .[grep("2015", .)] %>% 
  .[1:5] %>%
  gsub("/report/detail/","http://www.icaifu.com/report/detail/",.)
```

安信分析师

<iframe src="`r link[1]`" style="width:100%; height:420px;">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="`r link[1]`">
  全屏查看
</a>
</p>

-------------------------------------------------------------------------------------------

<iframe src="`r link[2]`" style="width:100%; height:420px;">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="`r link[2]`">
  全屏查看
</a>
</p>

-------------------------------------------------------------------------------------------

<iframe src="`r link[3]`" style="width:100%; height:420px;">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="`r link[3]`">
  全屏查看
</a>
</p>

-------------------------------------------------------------------------------------------

<iframe src="`r link[4]`" style="width:100%; height:420px;">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="`r link[4]`">
  全屏查看
</a>
</p>

-------------------------------------------------------------------------------------------

<iframe src="`r link[5]`" style="width:100%; height:420px;">
</iframe>

<p style="margin-top: 0px; text-align:right;">
<a target="_blank" 
href="`r link[5]`">
  全屏查看
</a>
</p>