---
layout:   post
title:    "i财富-行业分析"
category:  strategy
tags:     
    -  
    -   
description: 
published: false
status:    process
---


```{r echo=FALSE, warning=FALSE, message=FALSE}
rm(list = ls())
library(rvest)
library(beepr)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
url <- "http://www.icaifu.com/report/2/list.shtml"          ###  行业分析
link <- url %>% 
  read_html() %>% 
  html_nodes(".fund  td  a") %>% 
  html_attr("href") %>% 
  .[grep("2015", .)] %>% 
  .[1:30] %>%
  gsub("/report/detail/","http://www.icaifu.com/report/detail/",.)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
x <- link[1]
title <- x %>%
  read_html() %>%
  html_nodes(".pi1 h1") %>% 
  html_text()

date <- x %>%
  read_html() %>%
  html_nodes(".yan_to p") %>% 
  html_text() %>%
  .[grep("2015", .)]

main <- x %>%
    read_html()  %>% 
    html_nodes(".yan_t1 div") %>% 
    html_text() %>%
    gsub("\r\n \n\t|\t\t\r\n|\n\t|\t\t|\n", "\n \n", .)
```

## `r title`
[`r date`](`r x`)

`r main`


```{r echo=FALSE, warning=FALSE, message=FALSE}
x <- link[2]
title <- x %>%
  read_html() %>%
  html_nodes(".pi1 h1") %>% 
  html_text()

date <- x %>%
  read_html() %>%
  html_nodes(".yan_to p") %>% 
  html_text() %>%
  .[grep("2015", .)]

main <- x %>%
    read_html()  %>% 
    html_nodes(".yan_t1 div") %>% 
    html_text() %>%
    gsub("\r\n \n\t|\t\t\r\n|\n\t|\t\t|\n", "\n \n", .)
```

## `r title`
[`r date`](`r x`)

`r main`



```{r echo=FALSE, warning=FALSE, message=FALSE}
x <- link[3]
title <- x %>%
  read_html() %>%
  html_nodes(".pi1 h1") %>% 
  html_text()

date <- x %>%
  read_html() %>%
  html_nodes(".yan_to p") %>% 
  html_text() %>%
  .[grep("2015", .)]

main <- x %>%
    read_html()  %>% 
    html_nodes(".yan_t1 div") %>% 
    html_text() %>%
    gsub("\r\n \n\t|\t\t\r\n|\n\t|\t\t|\n", "\n \n", .)
```

## `r title`
[`r date`](`r x`)

`r main`


```{r echo=FALSE, warning=FALSE, message=FALSE}
article <- function(x){
title <- x %>%
  read_html() %>%
  html_nodes(".pi1 h1") %>% 
  html_text()

date <- x %>%
  read_html() %>%
  html_nodes(".yan_to p") %>% 
  html_text() %>%
  .[grep("2015", .)]

main <- x %>%
    read_html()  %>% 
    html_nodes(".yan_t1 div") %>% 
    html_text() %>%
    gsub("\r\n \n\t|\t\t\r\n|\n\t|\t\t|\n", "\n\n \n", .)

all <- c(x, title, date, main)
}
inf <-article(link[4])
```

## `r inf[2]`
[`r inf[3]`](`r inf[1]`)

`r inf[4]`


```{r echo=FALSE, warning=FALSE, message=FALSE}
x <- link[5]
title <- x %>%
  read_html() %>%
  html_nodes(".pi1 h1") %>% 
  html_text()

date <- x %>%
  read_html() %>%
  html_nodes(".yan_to p") %>% 
  html_text() %>%
  .[grep("2015", .)]

main <- x %>%
    read_html()  %>% 
    html_nodes(".yan_t1 div") %>% 
    html_text() %>%
    gsub("\r\n \n\t|\t\t\r\n|\n\t|\t\t|\n", "\n \n", .)
all <- c(x, title, date, main)
```

## `r all[2]`
[`r all[3]`](`r all[1]`)

`r all[4]`

