---
layout:   post
title:    "证券之星"
category: strategy
tags:     
    -  
    -   
description: 
published: false
status:    process
---


```{r echo=FALSE, warning=FALSE, message=FALSE}
# if you do not have it already, install the devtools package install.packages("devtools") 
# devtools::install_github("hadley/rvest") 
library(rvest)
```

<!------------------------------------------------------------------------------------------------------->
<!------------------------------------------------------------------------------------------------------->

## 板块掘金

```{r echo=FALSE, warning=FALSE, message=FALSE}
url <- "http://stock.stockstar.com/list/sectors.htm"

link <- url %>% 
  read_html(encoding="GB18030") %>% 
  html_nodes(".listtable  li  a") %>% 
  html_attr("href") %>% 
  .[1:10]


article <- function(x){
    link <- x
  
    title  <- x %>% 
    read_html(encoding="GB18030") %>% 
    html_nodes("h1") %>% 
    html_text()

  page.numbers <- x %>% 
    read_html(encoding="GB18030")  %>% 
    html_nodes("#Page a") %>% 
    html_text() %>%
    as.numeric()
  page.numbers <- page.numbers[1:length(page.numbers)-1]

  date <- x %>% 
    read_html(encoding="GB18030") %>% 
    html_nodes("#pubtime_baidu") %>% 
    html_text()

  url0 <- strsplit(x, "\\.shtml")

  url.new <- rep( NA, length(page.numbers) )
    for ( i in 1:length(page.numbers) ){
    url.new[i] <- paste(url0, "_", i, ".shtml", sep="")
  }

  text <- function(x){
    text <- x %>%
    read_html(encoding="GB18030")  %>% 
    html_nodes("#container-article  p") %>% 
    html_text()
  
    text <- text[3:length(text)-1]
  }

main <- lapply(url.new, text)

tidai <- function(x){
  # y = paste(x, collapse = '\t ============================================================================ \t')
  y = paste(x, collapse = '\n\n')
  return(y)
} 

  main <- main %>%
    sapply(., tidai) %>%
    as.character() %>%
    gsub("个股资料|操作策略|咨询高手|实盘买卖|基金持仓：,", "", .) %>%
    gsub("(\\（|\\）)","\n==========\n", .)
  
  all <- list(link, title, date, main)   ## all information: link, title, date, main
  return(all)
}

#inf = lapply(link[1:10], article)
##:
## inf[[]][[1]]: link
## inf[[]][[2]]: title
## inf[[]][[3]]: date
## inf[[]][[4]]: main
```

<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
inf = lapply(link[1], article)
```

### `r inf[[1]][[2]]`
[`r inf[[1]][[3]]`](`r inf[[1]][[1]]`)

`r inf[[1]][[4]]`

<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
inf = lapply(link[2], article)
```

### `r inf[[1]][[2]]`
[`r inf[[1]][[3]]`](`r inf[[1]][[1]]`)

`r inf[[1]][[4]]`
<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
inf = lapply(link[3], article)
```

### `r inf[[1]][[2]]`
[`r inf[[1]][[3]]`](`r inf[[1]][[1]]`)

`r inf[[1]][[4]]`
<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
inf = lapply(link[4], article)
```

### `r inf[[1]][[2]]`
[`r inf[[1]][[3]]`](`r inf[[1]][[1]]`)

`r inf[[1]][[4]]`
<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
inf = lapply(link[5], article)
```

### `r inf[[1]][[2]]`
[`r inf[[1]][[3]]`](`r inf[[1]][[1]]`)

`r inf[[1]][[4]]`
<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
inf = lapply(link[6], article)
```

### `r inf[[1]][[2]]`
[`r inf[[1]][[3]]`](`r inf[[1]][[1]]`)

`r inf[[1]][[4]]`

<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
inf = lapply(link[7], article)
```

### `r inf[[1]][[2]]`
[`r inf[[1]][[3]]`](`r inf[[1]][[1]]`)

`r inf[[1]][[4]]`

<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
inf = lapply(link[8], article)
```

### `r inf[[1]][[2]]`
[`r inf[[1]][[3]]`](`r inf[[1]][[1]]`)

`r inf[[1]][[4]]`

<!------------------------------------------------------------------------------------------------------->
