---
layout:   post
title:    "不甘心的这辈子"
category: 个人                                  
tags:     
		    - 时间  
	 	    - 一辈子
        - 生死
description: 
published: false
status:    process
---

我有一个朋友，虽然不怎么见面，也不常常往来，只是偶尔的通着电话，聊聊一些无关痛痒的话题。毕竟，我们都有自己的生活与世界，也活在不同的时光里，却每回有过联系，都是彼此相互诉说与倾听。他有他的故事，也许平时不愿让人知晓他坚强背后的忧伤，兴许对某个女生长期稚气般却执着的感情，他都会在电话那头自顾自己的说着，天涯海角的，他此时像是一个手持油笔的画家，恣意盎然的描述那个属于自己的星空。而我，只是静默的聆听着这样的诉说。

因为我知道，更多时候，我也是线端那头的他，变化的只是手里的那只画笔从深灰色到暗蓝色。

<!-- more -->

我不知道这样的通话保持了多少年的光阴，也许是从他离开高中之后。后来渐渐失去音讯，却又在我大学的某个晚上，出乎意料却时常期盼地接到他从北方的北方给我拨打的一通电话。话音那头，我甚至分不清逝去的时光去向那里，我们仿佛依旧是年少，依旧有许多的话，彼此不去理解，只是聆听着。

这样的时候，只是偶尔，却也温馨。

我的大学四年里，常常被各种针管与测试困扰着，被各种不理想的血糖测值烦扰，胰岛素与胰岛素，这些生物学的概念从未如此接近我。那时候，我也想象一个健康而完全的少年在绿茵场奔跑的样子，想象在广袤的原野间如风极驰，没有任何的羁绊与束缚。我想我上辈子是风，下辈子是雨，那么这辈子我最好还是安分些。

也就是在这样的四年里，我的朋友，他从远方拨打的一通通电话，给了我自由舒展的想象空间，给了我任自挥舞的浓墨笔尖，得以在我这张空白的即将清零的人生里，尽情的多写了几个字符，多绘了一丁点的颜色，以至于在这个北方昏暗的阴霾天里，得以看多一点希望。多少年后，我一直去努力回忆那些夜晚里到达的电话铃声，嘀嘀嘀嘀，声音缓缓却催促，低沉却是在这个无情的黑暗里照见最远方向的灯火，我也试图靠着这仅有的一点过去，伴我走完余下的路程。

来到厦门后，我的心情有了好转，再加上平时有到环岛路去慢跑，血糖水平得到了一定的控制。这样得意忘形的日子里，我却逐渐忘却了我那个可爱的朋友，还有他低沉的嗓音。我们比往日的偶尔更加偶尔的联系着，不高不低不急不慢，缓缓的如同巴赫的曲子，在夜间的小溪边叮咚的流淌，有时像是夏夜的虫鸣，各自吱了一声，便匆匆的收起赶场的伙计，各自回家。

直到有一天，我试着再像一只远走的老马循着旧日时光的足迹，不急不慢的敲打那几个熟悉的数字按钮，却等到了无穷无尽的等待。话线的那端，像是一个迷路的孩子，在外面的世界兴冲冲的玩耍了整天，却突然找不到回家的路，悄悄躲在某个幽暗的角落独自啜泣，音调时慢时快，却是同样的曲调不急不慢。我却殊不知，这个流浪的孩子，真的迷失在黑森林的暗道里，走不出来，找不到回家的路了。

我以前跟他说，我常常抱怨这辈子为病痛所折磨，堂堂男儿身，却被这样的无情的病魔捆绑在这无用而尽费热量的躯干里面。我这不甘心的一辈子。还有很多的事，已经不能完成的，没能想要完成的，还有来不及完成。

我的朋友，他还有很多事情没有完成的，却真的不能完成了。

我这不甘心的一辈子，已经在过去结束了。









