---
layout:   post
title:    "倾诉从结束到开始"
category:  
tags:     
    - 
    - 
description: 
published: false
status:    process
---

其实我以前对每一篇日志都有制作标签的习惯，这样方便日后查找方便。一个标签就如同贴在前面的门牌，让远走的游子方能找到后家的方向。可是，说真的，当我此刻在终端输入命令打开编辑器的时候，竟然不知道该往 `tags` 里面添加什么词语。是高兴的，可以值得欢呼雀跃的？还是忧伤的，独自躲在角落落寞的？抑或是平静的，日子如镜面恰似死水一潭？

这次的诺贝尔生理学奖颁发给了几位因为研究人脑神经系统的科学家，据新闻报道，他们似乎发现人的大脑原来早已「内置」了地位系统（俗称`GPS`）。纵然是掉队的飞鸟，也能找到大部队；可是啊，生命的个体，有时却或无奈或无辜或无聊或无畏的离开他所在的群落。集群生活是一种热闹，孤独有时却也是另一种美丽。如果科学真的发现人的神经系统可以做出基于地理信息的决策，那么一些人借着向心力逐渐向圆心靠拢，逐步走向权利的顶层，而这热闹甚至喧嚣的尘世，也存在着部分不受羁绊的个体，终日终身远离那个曾经痛爱的社群。这，或许是个体理性抉择的最有均衡点。

找不到标签的我，是否也已失去原先内置的 `GPS` 了呢？此刻，却也不知使用什么样的标签，来定位我所处于的地理，来定位我说处于的角色。

<!-- more -->

倾诉是一场互动的沟通，如同棋逢高手，高山流水，我们总是希望在浩淼尘世找到那个可以倾诉的对象。或许是你的父母，他们始终站在身后准备随时触手可及的宽慰；或许是你的对象，她一直陪伴在你的身边，不曾离去；或许是你的挚友，他们懂你的小情绪，理解你的不开心，有时也冲着你发火，可是你知道他们一直可以依靠。可是，是否想过，深藏在内心的自我，那个曾经是个孩子未来也不会长大的自我。我们有太多的话语，总是自言自语；我们有太多的委屈，想要找个角落躲起来独自舔着伤口。一次酣畅淋漓的倾诉，是从自我开始，也是从自我结束。

也许你对外界关闭了那个可以找到你的大脑版`GPS`，可是你始终关不掉的是深藏内心的自我。

W 在离去对我的打击倍感疼痛。或许一开始我只当做这原来只是一场玩笑，好好的一个人，却真的说走就走，不再相见。天边的云朵，在西边落幕，总是能在东方的晨曦找到些许的印记。可是这样的一个人，我却真的找不到了。或许当时我不敢失声痛哭，我怕躲在眼泪的雨幕背后是血淋淋的事实。所以把所有的`GPS`关闭了，安安静静的躲在一个无人的角落，以为这样便听不到所有的不幸，那些的伤悲。这样的经历曾经让我备受折磨，依稀多年不再，如今却如恶水潮涌，冰冷似刀。

我躲在被风伤害的角落，安静而无语的对着自己倾诉。关于 W 君，关于似水流年。这一次的倾诉没有开始，我也不知道它何时结束。




























































