---
layout:   post
title:    "针对90后的市场营销变革"
category: 分析 
tags:     
- 90后
- 市场
- 营销
description: 
published: false
status:    process
---

今天在网上看到一个[尼尔森的报告调查](http://bbs.pinggu.org/thread-3022380-1-1.html)，显示当前90后由于互联网与社交媒体的便捷而引发的一些消费习惯与他们的父辈具有不同的特征，这些包括

- 「正能量」的自我意识：乐观、个性、乐于享受
- 「若即若离」的人际关系：渴望独立又依赖“圈子”
- 「抓信息」的社会化媒体需求：保持新鲜，保持连接
- 「开放」的品牌态度：个性与品质的结合

针对第三点，报告也分析认为，现在针对90后群体的市场营销应该从提升产品的优质体验开始着手。

    “我们的定性分析也显示出由于90后长时间待在互联网和所有的社交媒体平台上，他们会较容易受到来自他们朋友圈中的好友、及社交网站上的各类‘意见领袖’的影响，这也证明了口碑传播作为一种市场营销方式，在年轻消费群体中扮演越来越重要的角色。相比在普通的门户网站或是论坛上投放一个一般性的广告，精准的市场营销策略，或是一个创新的营销活动（如嵌入式广告或是微信营销等），或许对90后消费者更奏效，”刘晓彬说道。
    
这个与我之前在 Coursera 上面看到说在新的互联网媒介环境下，市场营销策略的重大变化。从原来的单纯关注 Market Share 到后来注重产品的差异化策略，强调 Customer Share，等到了互联网在刚开始发展的阶段，人们意识到要将产品体验与产品价值结合在一起，从而将市场营销提升到 Experience Share 的高度。可是后来消费者逐渐发现，由于互联网所带来的这种信息沟通交流的便捷性，其实是可以把这种对产品的体验放大到社交群体里面，与好友一起分享对某个产品、某次体验、某类信息的个人评价，而正是这种社交媒体的放大作用，使得越来越多的企业开始关注消费者对自身价值创造的，对企业价值与远景的认可。这就到达了 Trust Share 的境界了。

现在回过头来看企业针对90后的市场营销，其实就是对 Trust Share 的争夺。我们现在讲究自媒体营销，讨论微信营销，这些营销手段的背后，企业家应该看到对消费者 Trust Share 的战略重视。传统企业也好，新兴互联网企业也罢，重要的，应该思考如何能够给消费者带来共同认可的产品价值与企业远景。也就是这种认可，才能带来 Trust Share 的提升。




