<!-- 
---
layout:   post
title:    "国睿科技"
category: 股票 
tags:     
- 军工
- 国睿
- 电子
description: 
published: false
status:    process
---
--->

## 集团简介

[国睿集团](http://www.glarun.com/company.asp)是中国电子科技集团公司第十四研究所（以下简称“十四所”）民品产业发展的平台，下辖多家控股公司，其母公司国睿集团有限公司由十四所全资设立，注册成立于2007年，注册资本金1.5亿元人民币。

　　十四所是我国电子信息领域中历史久、规模大、专业覆盖面广、研发力量强、技术成果丰富的大型综合性高技术研究所。拥有天线与微波国家级重点实验室，江苏省城市轨道交通信号工程技术研究中心、EMC实验室、综合环境实验中心、柔性加工中心等优质资源；拥有一支包括2名中国工程院院士在内的优秀员工队伍，现有在职职工5000人左右，其中科研人员占60%以上，包括120余名国家、省部级有突出贡献中青年专家、享受政府特殊津贴专家，1000余名高工与研究员级高工。

　　十四所先后承担了两弹一星、载人航天、登月工程、奥运工程、三峡工程等重大工程任务，为国防现代化事业和国民经济建设做出了重要贡献。为国家提供了众多大型装备，取得了多项科研成果，其中国家级成果奖60余项，部、省级成果奖400余项。为国睿集团民品产业健康、快速发展提供了良好的技术保障条件。

　　国睿集团依托十四所的技术、品牌等优质资源和多年来从事民品产业积累的成果，重点发展交通电子、供应链集成服务、微波与通信、软件与信息服务、能源电子和高端芯片等相关产业。

### 集团荣誉

国睿集团先后获得 「南京市高成长科技创新型百优企业」、「南京市20家优秀创新型企业」等荣誉，是南京市重点支持的「再造十家百亿企业集团」之一。

　　国睿集团的气象雷达继全国「十运会」夺目亮相并受到政府表彰之后，2008年获中国气象局颁发的「奥运会、残奥会」气象保障先进集体奖牌，2009年获首都60周年庆祝活动北京市筹备委员会气象服务组的奖牌；空管二次雷达2011年获得了DLD-100C型民航二次雷达使用许可证，成为国产空管二次雷达首家获得民航许可证的单位；具有自主知识产权的TD-SCDMA智能天线项目荣获国家发改委授予的“国家高技术产业化十年成就奖”。

### 公司的组织架构

[!组织架构](http://www.glarun.com/company.asp?tid=47)

### 企业文化

#### 传播语：眼界决定未来
　　眼界源于开阔的视野和敏锐的感知。放眼世界，才能洞悉瞬息万变的市场趋势；眼界来自前瞻的目光和深邃的思考。放眼未来，才能把握企业发展的战略；眼界始于高远的抱负和宽广的胸襟。放眼全局，才能运筹帷幄之中，决胜千里之外。

　　作为员工，个人的眼界决定了职业的发展，只有心胸开阔、顾全大局、着眼未来、才能贡献集体，成就事业。

　　作为组织，企业的眼界决定了事业的空间，团队的眼界决定了组织的未来，要具有“千里慧眼”，积极拓展业务，不能固守安逸，而应不懈进取。

　　“欲穷千里目，更上一层楼”，国睿集团立志成为国际一流的电子信息企业集团，最终实现知识价值最大化，就需要每一位国睿人在脚踏实地之余还要志存高远；需要每一位国睿人用求实的心态做现在，用发展的眼光谋未来。
 
#### 核心价值观：尽责、创新
　　我们崇尚“尽责、创新”的核心价值观，树立尽责之本，铸造创新之魂。尽责是企业生存的依托，我们倡导一切个体和集体的尽责行为。尽责是一种品质，折射着员工在本职岗位上恪尽职守，为国睿集团的发展默默奉献的赤胆忠心；尽责是一份荣誉，源于员工对集体利益的服从、维护和忠诚，超越本职工作，视国睿集团的发展为己任的可贵追求；尽责是一种行动，是执行力的有效支撑。

　　创新是企业持续发展的动力，我们支持一切推动国睿集团发展的创新。我们呼唤观念创新，敢于打破一切被传统禁锢的落后的僵化的思想观念，树立勇于创新、争先创新的思想作风；我们提倡管理创新，努力通过与时俱进、以人为本的管理变革，持续改进管理方法，营造不拘一格图发展的氛围，有效提高企业运作效率；我们鼓励有建树的技术创新，品质领先源于技术超前，科技超前才能引领行业。
 
### 企业愿景：做国际一流电子信息企业集团
　　做国际一流电子信息企业集团，是党和国家赋予国睿的神圣使命；是我们适应市场法则、顺应市场发展的充分体现；更是我们全体员工的坚定信念。

- 做国际一流电子信息企业集团，就是要贯彻科学的发展观，在规模、技术、市场上牢固树立争做“国际一流”的目标；就是要以顾客为关注焦点，持续为顾客提升价值；就是要立足国睿集团的研发优势，在我们从事的产业领域赢得卓越声誉。
- 做国际一流电子信息企业集团，就是要以市场为导向，以资本技术为纽带，以现代企业为主体，集研发、设计、制造、服务、物流与相关配套产业为一体，推动企业又好又快可持续发展。
- 做国际一流电子信息企业集团，就是要竭尽全力为员工提供实现自我价值、自我发展的广阔舞台和巨大空间，并在企业发展的同时，与员工共享物质财富与精神财富。

未来的国睿集团将以强大的实力与卓越的贡献在国际电子信息产业舞台上赢得尊重。

### 社会责任 

- 坚持依法诚信经营，自觉树立国企良好形象
- 注重内部管理，积极维护安全稳定和谐发展
- 推进自主创新和技术进步，实现民品产业稳步健康增长
- 培育新兴产业，带动地方产业发展
- 节约环保，争做表率

### 相关新闻

- [公司最新消息](http://irm.p5w.net/ssgs/S600562/)
  - [集团要闻](http://www.glarun.com/news.asp?tid=13)
  - [行业资讯](http://www.glarun.com/news.asp?tid=46)
  - [培训活动](http://www.glarun.com/news.asp?tid=27)
- [公司主产品介绍](http://www.glarun.com/pro.asp)

<!--
- [三大国内“首次”让新型电车添彩现代都市](http://www.glarun.com/xnews.asp?nid=881)
- [《新华网》：国睿集团以领先科技为智慧青奥“保驾护航”](http://www.glarun.com/xnews.asp?nid=879)
-->

## 公司的主要产业版块

### 交通电子

#### 轨道交通

  积极打造国内领先、国际先进的轨道交通总承包平台,以PMC、EPC、BT、BOT、PPP等总承包模式，实施整条轨道交通线路总承包、机电设备系统总承包和专业系统总承包。掌握专业系统关键技术，具备核心设备自主研制能力，成功研发信号、综合自动化、牵引等系统关键设备。1999年被原国家计委确定为“城市轨道交通信号系统国产化总成单位”，成功研制了具有自主知识产权的国产化列车自动监控（ATS）、计算机联锁（CBI）、列车自动防护（ATP）、列车自动驾驶（ATO）、车地通信（DCS）等系列产品。 
    
  先后承接了南京、苏州、哈尔滨、上海等城市20多条地铁线路的总包和专业系统工程项目，形成“总承包带动专业系统，专业系统支撑总承包”的良性互动局面。

#### 空中交通

主要包括航空管制雷达、通用航空和机场信息系统。

- 空管监视系统

    提供空管监视系统整体解决方案，拥有包括二次监视雷达、多点定位系统、机场场面监视雷达等多个系列化产品，实现飞机航路、进近、起降和机场场面的全空域监视，为空管提供精确的目标位置信息。2011年，DLD-100C型二次监视雷达获《民用航空空中交通通信导航监视设备使用许可证》。 

- 通用航空

    提供通用航空系统整体解决方案，开展通用航空系统集成总包建设和通用航空运营服务业务。

- 机场信息系统

    最先进入机场航站楼信息系统建设领域单位之一，集设计、咨询、项目建设管理、软件开发于一体，具有机场空管工程及航站楼系统工程专业承包资质，提供整套机场航站楼信息系统整体解决方案，先后完成北京、南京、深圳、海口和刚果、阿富汗等国内外二十多个机场信息系统建设。
    
#### 智能交通

国内最早从事城市道路交通智能化相关产品及系统研制的单位之一。与国际知名企业合作，研制出具有国际先进水平的城市交通管理综合信息平台及系列化产品，已广泛应用于北京、南京、广州、武汉、南昌、深圳、青岛等国内城市，并出口海外市场。 

主要业务领域

    城市交通管理信息平台、城市交通信号控制系统、城市交通智能诱导系统、高速公路智能管理、停车诱导及停车场管理、大型城市枢纽信息化管理等。
    
#### 海事交通

- 边海防信息系统 
    
    作为我国最先研制边海防信息系统的单位之一，提供陆地、海洋边境监控系统整体解决方案，融合多种平台数据，全面及时掌握综合态势，进行指挥调度和应急处置，确保边海防安全，产品成功应用我国广州、深圳等沿海城市。 

- 航道信息化

    国内最先开始船闸控制和航道信息化的研制和工程实施的单位之一，率先推出了船闸集散制控和管控一体化的设计理念，并成功运用于三峡工程和京杭运河联网系统，多项船闸软硬件控制工艺和信息技术已逐渐成为行业模板和标准，先后实施了包括三峡永久船闸、葛洲坝船闸、连云港港疏港信息化航道等30多项大型系统工程。  
    
### 供应链集成服务    

以供应链整合为基础，以信息化手段为支撑，以电子商务（中电易采网）为平台，面向国内外客户提供集采购、销售、仓储、配送以及设计、检测、认证、培训、咨询等为一体的供应链整体解决方案。[中电易采网](/https://www.ec-line.cn/)，2010年中电易采网正式运营，为客户提供在线电子元器件采购与销售、设计服务、技术发布、技术交流、在线招标等一体化供应链服务。

### 微波与通信

#### 气象雷达
率先研制出我国第一套双线偏振天气雷达、有源相控阵风廓线雷达，以国家“863”项目为牵引，研制成功新一代“信息化、网络化、系统化”气象探测系统，已成功应用于多个气象业务平台建设。

#### 无线通信
作为电子信息领域的国家队，拥有国家级天线与微波技术重点实验室，是工信部TD-SCDMA重大专项的技术依托单位；成功研制3G系列化天线产品，成为国内三大运营商的主要供应商；正在积极开展“新一代宽带无线移动通信网”国家科技重大专项和5G的相关技术产品的研制。2008年荣获国家发改委颁发的“国家高技术产业化十年成就奖”。

#### 卫星通信
 依托多年积累的卫星通信、遥感探测技术优势，积极参与我国北斗导航定位技术的产品研制工作，成功研发北斗一代/二代的手持、车载式定位与导航系列化产品，成为国内领先的北斗产品知名供应商。产品广泛应用于航空、航海、测量、通信、电力、气象、交通、国防等多个领域。

### 软件与信息服务

#### 企业信息化
依托多年的信息化软件自主研发、系统集成技术积累，高起点进入企业信息化产业，以“精益设计、精益制造、精益管理、精益保障”为核心，着力推进两化深度融合，构建覆盖产品设计、生产制造、综合保障、协同办公以及科研生产管理等全过程的先进企业信息化平台,致力于为研发制造类企业提供信息化整体解决方案和一站式服务。2013年获得“国家工业化和信息化深度融合重点示范企业”称号。

#### 场馆赛事信息化
国内最大的LED显示系统制造商之一，承担了北京奥运50%以上的显示系统项目，以及国庆阅兵、上海世博会等大型活动、大型场馆项目，延伸进入体育赛事信息系统领域。

#### 农业信息化
基于现代信息技术成果，集成网络技术、物联网技术、传感器技术和无线通信技术等先进技术，凭借丰富的经验，构建覆盖农业生产、加工、销售全过程的企业信息化管控平台，实现绿色农业、产业、城镇三大体系的信息化应用和智能化服务。
 
#### 港口信息化
以港口业务的电子化、网络化和自动化，实现港口与船务公司、铁路、公路、场站、货代、仓储等的无缝连接，以及港口与海关、海事、商检等管理部门的信息一体化 。

#### 警务安防信息化
为公共安全部门提供应急事件处理、要人要地保卫管理等的一体化指挥控制系统。

### 能源电子
#### 光伏发电
- 光伏逆变器及电站系统

    研制了具有自主知识产权的3kW, 15kW, 30kW, 100kW ，500KW等系列化光伏逆变器，广泛应用于商用/住宅光伏电站。

- 双向储能逆变器、

    作为电网与储能系统之间的重要接口设备，适用于各类电池储能系统。在独立的系统环境下（即并网系统，孤岛系统，混合系统中） 能够提供削峰填谷、应急独立逆变功能、灵活接受电网的调度指令、动/静态电网支撑以及无功功率补偿等。

#### 高功率脉冲电源
作为业内知名品牌，广泛应用于安全与反恐检查、工业探测、医用放疗、高功率微波武器等领域。

#### 分布式环境能源系统

- 合同能源管理：多能耦合供能系统

    结合区域综合优势，将太阳能、生物质能、风能和地热能等多种可再生能源和其它分布式能源结合，进行耦合控制，打造多能互补、智能联供低碳绿色建筑，并以多能耦合互补技术和区域性能源规划为基础，为低碳化城镇、智能园区、智慧城市建设提供综合能源管控的整体解决方案，并通过节能投资、建设与服务管理，实现效能利用最优化。 
    
- 系列化产品

    国内专业的节能设备制造商、节能服务提供商，除拥有完整的水地源热泵产品系列外，产品涵盖常规商用空调、末端设备、特种空调等多种设备。
    
    
    
    
    
    
    
    
