---
layout:   post
title:    "量化金融资料推荐"
category: share 
tags:     
    -  量化
    -  金融
description: 
published: false
status:    process
---

# Quant


- [QuantStart](https://www.quantstart.com/)
    
    量化金融模型介绍。
    
    <iframe src="https://www.quantstart.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [QuantStrat TradeR](https://quantstrattrader.wordpress.com/): Trading, QuantStrat, R, and more.

    *QuantStrat TradeR* 是一个介绍如何使用 *R* 来开发量化交易策略的网站，同时会把相应实现的代码分享出来，从而满足可复制与可实现的功能。
    
    <iframe src="https://quantstrattrader.wordpress.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>
    

- [Alvarez Quant Trading](http://alvarezquanttrading.com/): Quant Trading

    
    介绍量化金融的前沿理论与策略。
    
    <iframe src="http://alvarezquanttrading.com/blog/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Eran Raviv](http://eranraviv.com/category/blog/): 量化金融工程师
    
    量化金融与 *R* 代码。
    
    <iframe src="http://eranraviv.com/category/blog/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Quantitative Research and Trading](http://jonathankinlay.com/)
    
    量化金融理论研究与交易策略。
    
    <iframe src="http://jonathankinlay.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Keplerian Finance](http://keplerianfinance.com/): Exploring the boundaries of quantitative finance 
    
    量化金融研究。
    
    <iframe src="http://keplerianfinance.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Price Action Lab Blog](http://www.priceactionlab.com/Blog/)
    
    证券市场分析。
    
    <iframe src="http://www.priceactionlab.com/Blog/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Quant News](http://www.quantnews.com/): The latest research and news for quantitative traders 
    
    金融市场各种新闻与 *Rumors*。
    
    <iframe src="http://www.quantnews.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Systerm Trader](http://systemtradersuccess.com/)
    
    市场分析与资讯。
    
    <iframe src="http://systemtradersuccess.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Following the Trend](http://www.followingthetrend.com/)
    
    趋势交易策略。
    
    <iframe src="http://www.followingthetrend.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [CSSA](https://cssanalytics.wordpress.com/): new concepts in quantitative research
    
    量化金融研究前沿。
    
    <iframe src="https://cssanalytics.wordpress.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Au.Tra.Sy blog](http://www.automated-trading-system.com/): Automated Trading System
    
    使用 `R` 制作金融分析图表，做得相当的美观。
    
    <iframe src="http://www.automated-trading-system.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Anthony FJ Garner](https://anthonyfjgarner.net/)
    
    量化与资产配置。
    
    <iframe src="https://anthonyfjgarner.net/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Greenbackd](https://greenbackd.com/): Deep value, contrarian, and activist investment
    
    主动管理型量化金融。。
    
    <iframe src="https://greenbackd.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [The Mathematical Investor](http://www.financial-math.org/blog/): Mathematicians muse on money
    
    一个数学家对量化金融的策略。
    
    <iframe src="http://www.financial-math.org/blog/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [iMarketSignals](http://imarketsignals.com/blog/)
    
    市场交易策略信号捕捉。
    
    <iframe src="http://imarketsignals.com/blog/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Inovance](https://inovancetech.com/blogtitles.html)
    
    理解策略。
    
    <iframe src="https://inovancetech.com/blogtitles.html" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [MEB Faber Research](http://mebfaber.com/)
    
    股票市场与投资。
    
    <iframe src="http://mebfaber.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Mechanical Forex](http://mechanicalforex.com/)
    
    外汇交易。
    
    <iframe src="" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Six Figure Investing](http://sixfigureinvesting.com/)
    
    量化交易。
    
    <iframe src="http://sixfigureinvesting.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Trading Volatility](http://www.tradingvolatility.net/p/home_3.html)
    
    波动率模型。
    
    <iframe src="http://www.tradingvolatility.net/p/home_3.html" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Volatility Made Simple](http://volatilitymadesimple.com/blog/)
    
    波动率交易模型。
    
    <iframe src="http://volatilitymadesimple.com/blog/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Dual Momentum](http://www.dualmomentum.net/): information and research review by Gary Antonacci
    
    动能策略模型。
    
    <iframe src="http://www.dualmomentum.net/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [The R Trader](http://www.thertrader.com/)
    
    量化交易与 `R`。
    
    <iframe src="http://www.thertrader.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [DTR Trading](http://dtr-trading.blogspot.com/)
    
    期权交易策略。
    
    <iframe src="http://dtr-trading.blogspot.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Quantitative Systematic Market Analysis](http://qusma.com/)
    
    市场分析。
    
    <iframe src="http://qusma.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Alpha Hive](https://alphahive.wordpress.com/):Application Of R To Topics In Finance & Economics
    
    使用 `R` 来做量化分析。
    
    <iframe src="https://alphahive.wordpress.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Dynamic Hedge](http://www.dynamichedge.com/)
    
    对冲策略。
    
    <iframe src="http://www.dynamichedge.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Quant at Risk](http://www.quantatrisk.com/):Quantitative Analysis, Risk Management, Modelling, Algo Trading, and Big Data Analysis
    
    量化交易分析。
    
    <iframe src="http://www.quantatrisk.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [RRSP Strategy](https://rrspstrategy.wordpress.com/)
    
    量化策略。
    
    <iframe src="https://rrspstrategy.wordpress.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Computational Finance Blog](http://www.turingfinance.com/computational-finance-blog/)
    
    计算金融。
    
    <iframe src="http://www.turingfinance.com/computational-finance-blog/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Research Notebook](http://www.alexchinco.com/)
    
    量化模型。
    
    <iframe src="http://www.alexchinco.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Compounding My Interests](http://compoundingmyinterests.com/)
    
    金融理论分析。
    
    <iframe src="http://compoundingmyinterests.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Quantitative Trading](http://epchan.blogspot.com/)
    
    量化交易模型。
    
    <iframe src="http://epchan.blogspot.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Robot Wealth](http://robotwealth.com/): Applying science to trading and investment
    
    交易策略。
    
    <iframe src="http://robotwealth.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [FOSS TRADING](http://blog.fosstrading.com/): ALGORITHMIC TRADING WITH FREE OPEN SOURCE SOFTWARE
    
    算法交易策略及开放数据。
    
    <iframe src="http://blog.fosstrading.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Quantivity](https://quantivity.wordpress.com/): Uncommon Returns through Quantitative and Algorithmic Trading
    
    算法交易模型。
    
    <iframe src="https://quantivity.wordpress.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Tr8dr](https://tr8dr.wordpress.com/)
    
    量化交易与策略。
    
    <iframe src="https://tr8dr.wordpress.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [Quintuitive](http://www.quintuitive.com/): Quantitatively Intuitive Views on Markets
    
    量化交易与策略。
    
    <iframe src="http://www.quintuitive.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [The Practical Quant](http://practicalquant.blogspot.com/)
    
    量化交易员需要了解的科技前沿信息。
    
    <iframe src="http://practicalquant.blogspot.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>















# R

- [QuantLib](http://quantlib.org/index.shtml): A free/open-source library for quantitative finance
    
    `R` 扩展软件包。
    
    <iframe src="http://quantlib.org/index.shtml" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Timely Portfolio](http://timelyportfolio.blogspot.com/)
    
    使用 `R` 制作金融分析图表，做得相当的美观。
    
    <iframe src="http://timelyportfolio.blogspot.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


- [R-metrics](https://www.rmetrics.org/): The premier open source software solution for teaching and training quantitative finance
    
    一个用于处理金融时间序列的 `R package`。
    
    <iframe src="https://www.rmetrics.org/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Programm-R](http://www.programmingr.com/)
    
    `R` 编程相关的资源。
    
    <iframe src="http://www.programmingr.com/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>








# Data Resources

- [The UK Stock Market](http://stockmarketalmanac.co.uk/)
    
    英国金融市场的数据及图表。
    
    <iframe src="http://stockmarketalmanac.co.uk/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Portfolio Probing](http://www.portfolioprobe.com/blog/)
    
    美国金融市场数据。
    
    <iframe src="http://www.portfolioprobe.com/blog/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

- [Quantificable Edges](http://quantifiableedges.com/blog/)
    
    美国金融市场数据。
    
    <iframe src="http://quantifiableedges.com/blog/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>

# Visualization

- [Explained Visually](http://setosa.io/ev/)
    
    数学中一些常用概念的可视化，对于抽象的数学含义给出了图形说明。
    
    <iframe src="http://setosa.io/ev/" style="width:90%; height:350px; margin-left: 5%; bmargin-right: 5%;">
    </iframe>


