---
layout:   post
title:    "量化金融中常用的R软件包"
category:  share
tags:     
    -  量化
    -  金融
description: 
published: false
status:    process
---

<p><strong>Standard regression models</strong></p>
<ul>
<li>A detailed overview of the available regression methodologies is provided by the <a href="http://cran.r-project.org/web/views/Econometrics.html" target="_blank" rel="nofollow">Econometrics</a> task view. This is complemented by the <a href="http://cran.r-project.org/web/views/Robust.html" target="_blank" rel="nofollow">Robust</a> which focuses on more robust and resistant methods.</li>
<li>Linear models such as ordinary least squares (OLS) can be estimated by (from by the stats package contained in the basic R distribution). Maximum Likelihood (ML) estimation can be undertaken with the standard function. Many other suitable methods are listed in the <a href="http://cran.r-project.org/web/views/Optimization.html" target="_blank" rel="nofollow">Optimization</a> view. Non-linear least squares can be estimated with the function, as well as with from the <a href="http://cran.r-project.org/web/packages/nlme/index.html" target="_blank" rel="nofollow">nlme</a> package.</li>
<li>For the linear model, a variety of regression diagnostic tests are provided by the <a href="http://cran.r-project.org/web/packages/car/index.html" target="_blank" rel="nofollow">car</a>, <a href="http://cran.r-project.org/web/packages/lmtest/index.html" target="_blank" rel="nofollow">lmtest</a>, <a href="http://cran.r-project.org/web/packages/strucchange/index.html" target="_blank" rel="nofollow">strucchange</a>, <a href="http://cran.r-project.org/web/packages/urca/index.html" target="_blank" rel="nofollow">urca</a>, and <a href="http://cran.r-project.org/web/packages/sandwich/index.html" target="_blank" rel="nofollow">sandwich</a> packages. The <a href="http://cran.r-project.org/web/packages/Rcmdr/index.html" target="_blank" rel="nofollow">Rcmdr</a> and <a href="http://cran.r-project.org/web/packages/Zelig/index.html" target="_blank" rel="nofollow">Zelig</a> packages provide user interfaces that may be of interest as well.</li>
</ul>
<p><strong>Time series</strong></p>
<ul>
<li>A detailed overview of tools for time series analysis can be found in the <a href="http://cran.r-project.org/web/views/TimeSeries.html" target="_blank" rel="nofollow">TimeSeries</a> task view. Below a brief overview of the most important methods in finance is given.</li>
<li>Classical time series functionality is provided by the and commands in the basic R distribution.</li>
<li>The <a href="http://cran.r-project.org/web/packages/dse/index.html" target="_blank" rel="nofollow">dse</a> and <a href="http://cran.r-project.org/web/packages/timsac/index.html" target="_blank" rel="nofollow">timsac</a> packages provide a variety of more advanced estimation methods; <a href="http://cran.r-project.org/web/packages/fracdiff/index.html" target="_blank" rel="nofollow">fracdiff</a> can estimate fractionally integrated series; <a href="http://cran.r-project.org/web/packages/longmemo/index.html" target="_blank" rel="nofollow">longmemo</a> covers related material.</li>
<li>For volatility modeling, the standard GARCH(1,1) model can be estimated with the function in the <a href="http://cran.r-project.org/web/packages/tseries/index.html" target="_blank" rel="nofollow">tseries</a> package. Rmetrics (see below) contains the <a href="http://cran.r-project.org/web/packages/fGarch/index.html" target="_blank" rel="nofollow">fGarch</a> package which has additional models. The <a href="http://cran.r-project.org/web/packages/rugarch/index.html" target="_blank" rel="nofollow">rugarch</a> package can be used to model a variety of univariate GARCH models with extensions such as ARFIMA, in-mean, external regressors and various other specifications; with methods for fit, forecast, simulation, inference and plotting are provided too. The <a href="http://cran.r-project.org/web/packages/rmgarch/index.html" target="_blank" rel="nofollow">rmgarch</a> builds on it to provide the ability to estimate several multivariate GARCH models. The <a href="http://cran.r-project.org/web/packages/betategarch/index.html" target="_blank" rel="nofollow">betategarch</a> package can estimate and simulate the Beta-t-EGARCH model by Harvey. The <a href="http://cran.r-project.org/web/packages/bayesGARCH/index.html" target="_blank" rel="nofollow">bayesGARCH</a> package can perform Bayesian estimation of a GARCH(1,1) model with Student's t innovations. For multivariate models, the <a href="http://cran.r-project.org/web/packages/ccgarch/index.html" target="_blank" rel="nofollow">ccgarch</a> package can estimate (multivariate) Conditional Correlation GARCH models whereas the<a href="http://cran.r-project.org/web/packages/gogarch/index.html" target="_blank" rel="nofollow">gogarch</a> package provides functions for generalized orthogonal GARCH models. The <a href="http://cran.r-project.org/web/packages/AutoSEARCH/index.html" target="_blank" rel="nofollow">AutoSEARCH</a> package provides automated general-to-specific model selection of the mean and log-volatility of a log-ARCH-X model. The <a href="http://cran.r-project.org/web/packages/GEVStableGarch/index.html" target="_blank" rel="nofollow">GEVStableGarch</a> package can fit ARMA-GARCH or ARMA-APARCH models with GEV and stable conditional distributions. The <a href="http://cran.r-project.org/web/packages/lgarch/index.html" target="_blank" rel="nofollow">lgarch</a>package can estimate and fit log-Garch models.</li>
<li>Unit root and cointegration tests are provided by <a href="http://cran.r-project.org/web/packages/tseries/index.html" target="_blank" rel="nofollow">tseries</a>, and <a href="http://cran.r-project.org/web/packages/urca/index.html" target="_blank" rel="nofollow">urca</a>. The Rmetrics packages <a href="http://cran.r-project.org/web/packages/timeSeries/index.html" target="_blank" rel="nofollow">timeSeries</a> and <a href="http://cran.r-project.org/web/packages/fMultivar/index.html" target="_blank" rel="nofollow">fMultivar</a> contain a number of estimation functions for ARMA, GARCH, long memory models, unit roots and more. The <a href="http://cran.r-project.org/web/packages/CADFtest/index.html" target="_blank" rel="nofollow">CADFtest</a> package implements the Hansen unit root test.</li>
<li>The <a href="http://cran.r-project.org/web/packages/dlm/index.html" target="_blank" rel="nofollow">dlm</a> package provides Bayesian and likelihood analysis of dynamic linear models (ie linear Gaussian state space models).</li>
<li>The <a href="http://cran.r-project.org/web/packages/vars/index.html" target="_blank" rel="nofollow">vars</a> package offer estimation, diagnostics, forecasting and error decomposition of VAR and SVAR model in a classical framework.</li>
<li>The <a href="http://cran.r-project.org/web/packages/dyn/index.html" target="_blank" rel="nofollow">dyn</a> and <a href="http://cran.r-project.org/web/packages/dynlm/index.html" target="_blank" rel="nofollow">dynlm</a> are suitable for dynamic (linear) regression models.</li>
<li>Several packages provide wavelet analysis functionality: <a href="http://cran.r-project.org/web/packages/rwt/index.html" target="_blank" rel="nofollow">rwt</a>, <a href="http://cran.r-project.org/web/packages/wavelets/index.html" target="_blank" rel="nofollow">wavelets</a>, <a href="http://cran.r-project.org/web/packages/waveslim/index.html" target="_blank" rel="nofollow">waveslim</a>, <a href="http://cran.r-project.org/web/packages/wavethresh/index.html" target="_blank" rel="nofollow">wavethresh</a>. Some methods from chaos theory are provided by the package <a href="http://cran.r-project.org/web/packages/tseriesChaos/index.html" target="_blank" rel="nofollow">tseriesChaos</a>. <a href="http://cran.r-project.org/web/packages/tsDyn/index.html" target="_blank" rel="nofollow">tsDyn</a> adds time series analysis based on dynamical systems therory.</li>
<li>The <a href="http://cran.r-project.org/web/packages/forecast/index.html" target="_blank" rel="nofollow">forecast</a> package adds functions for forecasting problems.</li>
<li>The <a href="http://cran.r-project.org/web/packages/tsfa/index.html" target="_blank" rel="nofollow">tsfa</a> package provides functions for time series factor analysis.</li>
<li>The <a href="http://cran.r-project.org/web/packages/stochvol/index.html" target="_blank" rel="nofollow">stochvol</a> package implements Bayesian estimation of stochastic volatility using Markov Chain Monte Carlo.</li>
</ul>
<p><strong>Finance</strong></p>
<ul>
<li>The Rmetrics suite of packages comprises <a href="http://cran.r-project.org/web/packages/fArma/index.html" target="_blank" rel="nofollow">fArma</a>, <a href="http://cran.r-project.org/web/packages/fAsianOptions/index.html" target="_blank" rel="nofollow">fAsianOptions</a>, <a href="http://cran.r-project.org/web/packages/fBasics/index.html" target="_blank" rel="nofollow">fBasics</a>, <a href="http://cran.r-project.org/web/packages/fBonds/index.html" target="_blank" rel="nofollow">fBonds</a>, <a href="http://cran.r-project.org/web/packages/timeDate/index.html" target="_blank" rel="nofollow">timeDate</a> (formerly: fCalendar), <a href="http://cran.r-project.org/web/packages/fExoticOptions/index.html" target="_blank" rel="nofollow">fExoticOptions</a>, <a href="http://cran.r-project.org/web/packages/fExtremes/index.html" target="_blank" rel="nofollow">fExtremes</a>, <a href="http://cran.r-project.org/web/packages/fGarch/index.html" target="_blank" rel="nofollow">fGarch</a>, <a href="http://cran.r-project.org/web/packages/fImport/index.html" target="_blank" rel="nofollow">fImport</a>, <a href="http://cran.r-project.org/web/packages/fNonlinear/index.html" target="_blank" rel="nofollow">fNonlinear</a>, <a href="http://cran.r-project.org/web/packages/fOptions/index.html" target="_blank" rel="nofollow">fOptions</a>,<a href="http://cran.r-project.org/web/packages/timeSeries/index.html" target="_blank" rel="nofollow">timeSeries</a> (formerly: fSeries), <a href="http://cran.r-project.org/web/packages/fTrading/index.html" target="_blank" rel="nofollow">fTrading</a>, <a href="http://cran.r-project.org/web/packages/fUnitRoots/index.html" target="_blank" rel="nofollow">fUnitRoots</a> and contains a very large number of relevant functions for different aspect of empirical and computational finance.</li>
<li>The <a href="http://cran.r-project.org/web/packages/RQuantLib/index.html" target="_blank" rel="nofollow">RQuantLib</a> package provides several option-pricing functions as well as some fixed-income functionality from the QuantLib project to R.</li>
<li>The <a href="http://cran.r-project.org/web/packages/quantmod/index.html" target="_blank" rel="nofollow">quantmod</a> package offers a number of functions for quantitative modelling in finance as well as data acqusition, plotting and other utilities.</li>
<li>The <a href="http://cran.r-project.org/web/packages/portfolio/index.html" target="_blank" rel="nofollow">portfolio</a> package contains classes for equity portfolio management; the <a href="http://cran.r-project.org/web/packages/portfolioSim/index.html" target="_blank" rel="nofollow">portfolioSim</a> builds a related simulation framework. The <a href="http://cran.r-project.org/web/packages/backtest/index.html" target="_blank" rel="nofollow">backtest</a> offers tools to explore portfolio-based hypotheses about financial instruments. The <a href="http://cran.r-project.org/web/packages/stockPortfolio/index.html" target="_blank" rel="nofollow">stockPortfolio</a> package provides functions for single index, constant correlation and multigroup models. The <a href="http://cran.r-project.org/web/packages/pa/index.html" target="_blank" rel="nofollow">pa</a> package offers performance attribution functionality for equity portfolios.</li>
<li>The <a href="http://cran.r-project.org/web/packages/PerformanceAnalytics/index.html" target="_blank" rel="nofollow">PerformanceAnalytics</a> package contains a large number of functions for portfolio performance calculations and risk management.</li>
<li>The <a href="http://cran.r-project.org/web/packages/TTR/index.html" target="_blank" rel="nofollow">TTR</a> contains functions to construct technical trading rules in R.</li>
<li>The <a href="http://cran.r-project.org/web/packages/sde/index.html" target="_blank" rel="nofollow">sde</a> package provides simulation and inference functionality for stochastic differential equations.</li>
<li>The <a href="http://cran.r-project.org/web/packages/termstrc/index.html" target="_blank" rel="nofollow">termstrc</a> and <a href="http://cran.r-project.org/web/packages/YieldCurve/index.html" target="_blank" rel="nofollow">YieldCurve</a> packages contain methods for the estimation of zero-coupon yield curves and spread curves based the parametric Nelson and Siegel (1987) method with the Svensson (1994) extension. The former package adds the McCulloch (1975) cubic splines approach, the latter package adds the Diebold and Li approach. The<a href="http://cran.r-project.org/web/packages/SmithWilsonYieldCurve/index.html" target="_blank" rel="nofollow">SmithWilsonYieldCurve</a> construct the yield curve using the Smith-Wilson approach based on LIBOR and SWAP rates.</li>
<li>The <a href="http://cran.r-project.org/web/packages/vrtest/index.html" target="_blank" rel="nofollow">vrtest</a> package contains a number of variance ratio tests for the weak-form of the efficient markets hypothesis.</li>
<li>The <a href="http://cran.r-project.org/web/packages/gmm/index.html" target="_blank" rel="nofollow">gmm</a> package provides generalized method of moments (GMM) estimations function that are often used when estimating the parameters of the moment conditions implied by an asset pricing model.</li>
<li>The <a href="http://cran.r-project.org/web/packages/tawny/index.html" target="_blank" rel="nofollow">tawny</a> package contains estimator based on random matrix theory as well as shrinkage methods to remove sampling noise when estimating sample covariance matrices.</li>
<li>The <a href="http://cran.r-project.org/web/packages/opefimor/index.html" target="_blank" rel="nofollow">opefimor</a> package by contains material to accompany the Iacus (2011) book entitled "Option Pricing and Estimation of Financial Models in R".</li>
<li>The <a href="http://cran.r-project.org/web/packages/maRketSim/index.html" target="_blank" rel="nofollow">maRketSim</a> package provides a market simulator, initially designed around the bond market.</li>
<li>The <a href="http://cran.r-project.org/web/packages/BurStFin/index.html" target="_blank" rel="nofollow">BurStFin</a> and <a href="http://cran.r-project.org/web/packages/BurStMisc/index.html" target="_blank" rel="nofollow">BurStMisc</a> package has a collection of function for Finance including the estimation of covariance matrices.</li>
<li>The <a href="http://cran.r-project.org/web/packages/AmericanCallOpt/index.html" target="_blank" rel="nofollow">AmericanCallOpt</a> package contains a pricer for different American call options.</li>
<li>The <a href="http://cran.r-project.org/web/packages/VarSwapPrice/index.html" target="_blank" rel="nofollow">VarSwapPrice</a> package can price a variance swap via a portfolio of European options contracts.</li>
<li>The <a href="http://cran.r-project.org/web/packages/FinAsym/index.html" target="_blank" rel="nofollow">FinAsym</a> package implements the Lee and Ready (1991) and Easley and O'Hara (1987) tests for, respectively, trade direction, and probability of informed trading.</li>
<li>The <a href="http://cran.r-project.org/web/packages/parma/index.html" target="_blank" rel="nofollow">parma</a> package provides support for portfolio allocation and risk management applications.</li>
<li>The <a href="http://cran.r-project.org/web/packages/GUIDE/index.html" target="_blank" rel="nofollow">GUIDE</a> package provides a <em>GUI </em>for <em>DE </em>rivatives and contains numerous pricer examples as well as interactive 2d and 3d plots to study these pricing functions.</li>
<li>The <a href="http://cran.r-project.org/web/packages/SharpeR/index.html" target="_blank" rel="nofollow">SharpeR</a> package contains a collection of tools for analyzing significance of trading strategies, based on the Sharpe ratio and overfit of the same.</li>
<li>The <a href="http://cran.r-project.org/web/packages/RND/index.html" target="_blank" rel="nofollow">RND</a> package implements various functions to extract risk-neutral densities from option prices.</li>
<li><a href="http://cran.r-project.org/web/packages/LSMonteCarlo/index.html" target="_blank" rel="nofollow">LSMonteCarlo</a> can price American Options via the Least Squares Monte Carlo method</li>
<li>The <a href="http://cran.r-project.org/web/packages/BenfordTests/index.html" target="_blank" rel="nofollow">BenfordTests</a> package provides seven statistical tests and support functions for determining if numerical data could conform to Benford's law.</li>
<li>The <a href="http://cran.r-project.org/web/packages/OptHedging/index.html" target="_blank" rel="nofollow">OptHedging</a> package values call and put option portfolio and implements an optimal hedging strategy.</li>
<li>The <a href="http://cran.r-project.org/web/packages/markovchain/index.html" target="_blank" rel="nofollow">markovchain</a> package provides functionality to easily handle and analyse discrete Markov chains.</li>
<li>The <a href="http://cran.r-project.org/web/packages/ycinterextra/index.html" target="_blank" rel="nofollow">ycinterextra</a> package models yield curve interpolation and extrapolation using via the Nelson-Siegel, Svensson, or Smith-Wilson models, as well as Hermite cubic splines.</li>
<li>The <a href="http://cran.r-project.org/web/packages/tvm/index.html" target="_blank" rel="nofollow">tvm</a> package models provides functions for time value of money such as cashflows and yield curves.</li>
<li>The <a href="http://cran.r-project.org/web/packages/MarkowitzR/index.html" target="_blank" rel="nofollow">MarkowitzR</a> package provides functions to test the statistical signicance of Markowitz portfolios.</li>
<li>The <a href="http://cran.r-project.org/web/packages/egcm/index.html" target="_blank" rel="nofollow">egcm</a> package implements the Engle-Granger two-stage cointegration modeling procedure with a particular focus on pairs trading.</li>
<li>The <a href="http://cran.r-project.org/web/packages/pbo/index.html" target="_blank" rel="nofollow">pbo</a> package models the probability of backtest overfitting, performance degradation, probability of loss, and the stochastic dominance when analysing trading strategies.</li>
<li>The <a href="http://cran.r-project.org/web/packages/OptionPricing/index.html" target="_blank" rel="nofollow">OptionPricing</a> package implements rfficient Monte Carlo algorithms for the price and the sensitivities of Asian and European Options under Geometric Brownian Motion.</li>
</ul>
<p><strong>Risk management</strong></p>
<ul>
<li>Several packages provide functionality for Extreme Value Theory models: <a href="http://cran.r-project.org/web/packages/evd/index.html" target="_blank" rel="nofollow">evd</a>, <a href="http://cran.r-project.org/web/packages/evdbayes/index.html" target="_blank" rel="nofollow">evdbayes</a>, <a href="http://cran.r-project.org/web/packages/evir/index.html" target="_blank" rel="nofollow">evir</a>, <a href="http://cran.r-project.org/web/packages/extRemes/index.html" target="_blank" rel="nofollow">extRemes</a>, <a href="http://cran.r-project.org/web/packages/ismev/index.html" target="_blank" rel="nofollow">ismev</a>.</li>
<li>The packages <a href="http://cran.r-project.org/web/packages/CreditMetrics/index.html" target="_blank" rel="nofollow">CreditMetrics</a> and <a href="http://cran.r-project.org/web/packages/crp.CSFP/index.html" target="_blank" rel="nofollow">crp.CSFP</a> provide function for modelling credit risks.</li>
<li>The <a href="http://cran.r-project.org/web/packages/mvtnorm/index.html" target="_blank" rel="nofollow">mvtnorm</a> package provides code for multivariate Normal and t-distributions.</li>
<li>The Rmetrics package <a href="http://cran.r-project.org/web/packages/fExtremes/index.html" target="_blank" rel="nofollow">fExtremes</a> also contain a number of relevant functions.</li>
<li>The <a href="http://cran.r-project.org/web/packages/copula/index.html" target="_blank" rel="nofollow">copula</a> and <a href="http://cran.r-project.org/web/packages/fgac/index.html" target="_blank" rel="nofollow">fgac</a> packages cover multivariate dependency structures using copula methods.</li>
<li>The <a href="http://cran.r-project.org/web/packages/actuar/index.html" target="_blank" rel="nofollow">actuar</a> package provides an actuarial perspective to risk management.</li>
<li>The <a href="http://cran.r-project.org/web/packages/ghyp/index.html" target="_blank" rel="nofollow">ghyp</a> package provides generalized hyberbolic distribution functions as well as procedures for VaR, CVaR or target-return portfolio optimizations.</li>
<li>The <a href="http://cran.r-project.org/web/packages/ChainLadder/index.html" target="_blank" rel="nofollow">ChainLadder</a> package provides functions for modeling insurance claim reserves; and the <a href="http://cran.r-project.org/web/packages/lifecontingencies/index.html" target="_blank" rel="nofollow">lifecontingencies</a> package provides functions for financial and actuarial evaluations of life contingencies.</li>
<li>The <a href="http://cran.r-project.org/web/packages/frmqa/index.html" target="_blank" rel="nofollow">frmqa</a> package aims to collect functions for Financial Risk Management and Quantitative Analysis.</li>
<li>The <a href="http://cran.r-project.org/web/packages/ESG/index.html" target="_blank" rel="nofollow">ESG</a> package can be used to model for asset projection, a scenario-based simulation approach.</li>
<li>The <a href="http://cran.r-project.org/web/packages/riskSimul/index.html" target="_blank" rel="nofollow">riskSimul</a> package provides efficient simulation procedures to estimate tail loss probabilities and conditional excess for a stock portfolios where log-returns are assumed to follow a t-copula model with generalized hyperbolic or t marginals.</li>
</ul>
<p><strong>Books</strong></p>
<ul>
<li>The <a href="http://cran.r-project.org/web/packages/FinTS/index.html" target="_blank" rel="nofollow">FinTS</a> package provides an R companion to Tsay (2005), <em>Analysis of Financial Time Series </em>, 2nd ed. Wiley, and includes data sets, functions and script files to work some of the examples.</li>
<li>The <a href="http://cran.r-project.org/web/packages/NMOF/index.html" target="_blank" rel="nofollow">NMOF</a> package provides functions, examples and data from <em>Numerical Methods in Finance </em>by Manfred Gilli, Dietmar Maringer and Enrico Schumann (2011), including the different optimization heuristics such as Differential Evolution, Genetic Algorithms, Particle Swarms, and Threshold Accepting.</li>
</ul>
<p><strong>Data and date management</strong></p>
<ul>
<li>The <a href="http://cran.r-project.org/web/packages/its/index.html" target="_blank" rel="nofollow">its</a>, <a href="http://cran.r-project.org/web/packages/zoo/index.html" target="_blank" rel="nofollow">zoo</a> and <a href="http://cran.r-project.org/web/packages/timeDate/index.html" target="_blank" rel="nofollow">timeDate</a> (part of Rmetrics) packages provide support for irregularly-spaced time series. The <a href="http://cran.r-project.org/web/packages/xts/index.html" target="_blank" rel="nofollow">xts</a> package extends <a href="http://cran.r-project.org/web/packages/zoo/index.html" target="_blank" rel="nofollow">zoo</a> specifically for financial time series. See the<a href="http://cran.r-project.org/web/views/TimeSeries.html" target="_blank" rel="nofollow">TimeSeries</a> task view for more details.</li>
<li><a href="http://cran.r-project.org/web/packages/timeDate/index.html" target="_blank" rel="nofollow">timeDate</a> also addresses calendar issues such as recurring holidays for a large number of financial centers, and provides code for high-frequency data sets.</li>
<li>The <a href="http://cran.r-project.org/web/packages/fame/index.html" target="_blank" rel="nofollow">fame</a> package can access Fame time series databases (but also requires a Fame backend). The <a href="http://cran.r-project.org/web/packages/tis/index.html" target="_blank" rel="nofollow">tis</a> package provides time indices and time-indexed series compatible with Fame frequencies.</li>
<li>The <a href="http://cran.r-project.org/web/packages/TSdbi/index.html" target="_blank" rel="nofollow">TSdbi</a> package provides a unifying interface for several time series data base backends, and its SQL implementations provide a database table design.</li>
<li>The <a href="http://cran.r-project.org/web/packages/data.table/index.html" target="_blank" rel="nofollow">data.table</a> package provides very efficient and fast access to in-memory data sets such as asset prices.</li>
<li>The <a href="http://cran.r-project.org/web/packages/TFX/index.html" target="_blank" rel="nofollow">TFX</a> package provides an interface to the TrueFX (TM) service for free streaming real-time and historical tick-by-tick market data for interbank foreign exchange rates at the millisecond resolution.</li>
<li>The <a href="http://cran.r-project.org/web/packages/Rbitcoin/index.html" target="_blank" rel="nofollow">Rbitcoin</a> package offers access to Bitcoin exchange APIs (mtgox, bitstamp, btce, kraken) via public and private API calls and integration of data structures for all markets.</li>
<li>The <a href="http://cran.r-project.org/web/packages/TAQMNGR/index.html" target="_blank" rel="nofollow">TAQMNGR</a> package manages tick-by-tick (equity) transaction data performing 'cleaning', 'aggregation' and 'import' where cleaning and aggregation are performed according to Brownlees and Gallo (2006).</li>
<li>The <a href="http://cran.r-project.org/web/packages/bizdays/index.html" target="_blank" rel="nofollow">bizdays</a> package compute business days if provided a list of holidays.</li>
</ul>

</div></div>
